window.AcuarioNexoAdmin={version:'admin-panel-23-05-v1'};
(function(){
function E(v){return String(v||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function app(){return document.getElementById('app')}
function uid(){return window.u&&window.u.id?window.u.id:null}
function top(){return window.menu?window.menu():''}
function bottom(){return '<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="adminPanel()">🛠️<small>Admin</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>'}
function paint(h){if(app())app().innerHTML=top()+h+bottom();scrollTo(0,0)}
function adminEnabled(){try{return localStorage.getItem('acuarionexo_admin_enabled')==='1'}catch(e){return false}}
function enableAdmin(){try{localStorage.setItem('acuarionexo_admin_enabled','1')}catch(e){} adminPanel()}
function disableAdmin(){try{localStorage.removeItem('acuarionexo_admin_enabled')}catch(e){} goSection('Dashboard')}
window.adminPanel=function(){
 if(!uid())return paint('<section class="premium-block"><h2>🛠️ Admin</h2><p>Inicia sesión para usar el panel admin.</p></section>');
 if(!adminEnabled())return paint('<section class="premium-block"><h2>🛠️ Activar Panel Admin</h2><p>Panel privado para preparar fichas, fotos, Gemini manual y publicación. No consume créditos IA.</p><button class="primary" onclick="AcuarioNexoAdmin.enable()">Activar admin en este dispositivo</button></section>');
 paint('<section class="premium-block"><div class="block-head"><h2>🛠️ Panel Admin</h2><button onclick="AcuarioNexoAdmin.disable()">Ocultar</button></div><p>Centro privado para preparar contenido sin gastar créditos IA.</p><div class="dashboard-grid"><article><h3>📷 Studio Fotos</h3><p>Prepara fotos con fondo limpio y miniaturas.</p><button onclick="adminStudioFotos()">Abrir</button></article><article><h3>📋 Fichas</h3><p>Borradores, revisión y publicadas.</p><button onclick="adminFichas()">Ver fichas</button></article><article><h3>✨ Importar Gemini</h3><p>Genera prompt, pega respuesta y valida ficha.</p><button onclick="adminGemini()">Importar</button></article><article><h3>🐞 Testers</h3><p>Reportes, fallos y seguimiento.</p><button onclick="adminTesters()">Ver</button></article></div></section>')
};
window.adminStudioFotos=function(){paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>📷 Studio Fotos</h2><p>Preparador gratuito. Usa Canva o foto directa, luego guarda la ficha en Supabase.</p><label>Foto / exportación Canva</label><input type="file" accept="image/*" onchange="adminPhoto(this)"><input id="admFoto" type="hidden"><div id="admPrev" class="item">Sin foto</div><label>Nombre producto</label><input id="admNombre"><label>Marca</label><input id="admMarca"><label>Categoría</label><input id="admCat"><button class="primary" onclick="adminSaveDraft()">Guardar borrador</button><div id="admMsg"></div></section>')};
window.adminPhoto=function(inp){var f=inp.files&&inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){admFoto.value=e.target.result;admPrev.innerHTML='<img class="photo" src="'+e.target.result+'">'};r.readAsDataURL(f)};
window.adminGemini=function(){var prompt='Crea una ficha tecnica completa para AcuarioNexo. Devuelve JSON con: marca, nombre, categoria, resumen_corto, ficha_tecnica, dosis, advertencias, compatibilidad, reef_safe, parametros_relacionados. No inventes datos criticos.';paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>✨ Importar Gemini gratis</h2><p>1. Copia este prompt en Gemini web gratis. 2. Pega aquí la respuesta JSON. 3. Guarda borrador.</p><label>Prompt</label><textarea id="admPrompt">'+E(prompt)+'</textarea><label>Respuesta Gemini JSON</label><textarea id="admJson"></textarea><button class="primary" onclick="adminImportGemini()">Importar respuesta</button><div id="admMsg"></div></section>')};
window.adminImportGemini=function(){try{var j=JSON.parse(admJson.value);sessionStorage.setItem('nexoadmin_import',JSON.stringify(j));admMsg.innerHTML='<div class="success">JSON válido. Abre Studio Fotos para completar foto y guardar.</div>'}catch(e){admMsg.innerHTML='<div class="error">JSON no válido: '+E(e.message)+'</div>'}};
window.adminSaveDraft=async function(){var msg=document.getElementById('admMsg');try{if(!window.s)throw new Error('Supabase no disponible');var raw={};try{raw=JSON.parse(sessionStorage.getItem('nexoadmin_import')||'{}')}catch(e){}var row={user_id:uid(),estado:'borrador',modulo:'inventario',nombre:(admNombre&&admNombre.value)||raw.nombre||raw.producto||'Sin nombre',marca:(admMarca&&admMarca.value)||raw.marca||'',categoria:(admCat&&admCat.value)||raw.categoria||'',foto_limpia:(admFoto&&admFoto.value)||'',foto_thumb:(admFoto&&admFoto.value)||'',gemini_json:raw,resumen_corto:raw.resumen_corto||'',ficha_tecnica:raw.ficha_tecnica||raw.resumen_tecnico||'',dosis:raw.dosis||'',advertencias:raw.advertencias||'',compatibilidad:raw.compatibilidad||'',reef_safe:typeof raw.reef_safe==='boolean'?raw.reef_safe:null,design_source:'nexoadmin',template_size:'1080x1080'};var r=await window.s.from('nexoadmin_fichas').insert(row).select().single();if(r.error)throw r.error;msg.innerHTML='<div class="success">Borrador guardado en Supabase.</div>';sessionStorage.removeItem('nexoadmin_import')}catch(e){if(msg)msg.innerHTML='<div class="error">'+E(e.message)+'</div>'}};
window.adminFichas=async function(){paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>📋 Fichas</h2><div id="adminList">Cargando...</div></section>');try{var r=await window.s.from('nexoadmin_fichas').select('*').order('created_at',{ascending:false}).limit(30);if(r.error)throw r.error;var html=(r.data||[]).map(function(x){return '<article class="item"><h3>'+E((x.marca||'')+' '+(x.nombre||''))+'</h3><p><b>Estado:</b> '+E(x.estado)+' · <b>Publicado:</b> '+(x.publicado_en_app?'Sí':'No')+'</p><p>'+E((x.resumen_corto||x.ficha_tecnica||'').slice(0,180))+'</p><div class="grid2"><button onclick="adminPublish(\''+x.id+'\')">Publicar</button><button onclick="adminUnpublish(\''+x.id+'\')">Ocultar</button></div></article>'}).join('')||'<p class="notice">Sin fichas.</p>';document.getElementById('adminList').innerHTML=html}catch(e){document.getElementById('adminList').innerHTML='<div class="error">'+E(e.message)+'</div>'}};
window.adminPublish=async function(id){await window.s.from('nexoadmin_fichas').update({estado:'publicada',publicado_en_app:true,tester_visible:true,updated_at:new Date().toISOString()}).eq('id',id);adminFichas()};
window.adminUnpublish=async function(id){await window.s.from('nexoadmin_fichas').update({estado:'borrador',publicado_en_app:false,tester_visible:false,updated_at:new Date().toISOString()}).eq('id',id);adminFichas()};
window.adminTesters=function(){paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>🐞 Testers</h2><p class="notice">Preparado para reportes y seguimiento. Siguiente fase: tabla de fallos y actividad.</p></section>')};
window.AcuarioNexoAdmin.enable=enableAdmin;window.AcuarioNexoAdmin.disable=disableAdmin;
var old=window.goSection;window.goSection=function(n){if(n==='Admin')return adminPanel();return old?old(n):null};
})();
