window.AcuarioNexoAdmin={version:'admin-panel-23-05-v3-studio-simple'};
(function(){
function E(v){return String(v||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function app(){return document.getElementById('app')}
function uid(){return window.u&&window.u.id?window.u.id:null}
function top(){return window.menu?window.menu():''}
function bottom(){return '<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="adminPanel()">🛠️<small>Admin</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>'}
function paint(h){if(app())app().innerHTML=top()+h+bottom();scrollTo(0,0)}
function adminEnabled(){try{return localStorage.getItem('acuarionexo_admin_enabled')==='1'}catch(e){return false}}
function enableAdmin(){try{localStorage.setItem('acuarionexo_admin_enabled','1')}catch(e){} adminPanel()}
function disableAdmin(){try{localStorage.removeItem('acuarionexo_admin_enabled')}catch(e){} goSection('Dashboard')}
function injectAdminButton(){try{if(document.getElementById('adminFloatBtn'))return;var st=document.createElement('style');st.textContent='#adminFloatBtn{position:fixed;right:14px;bottom:102px;z-index:90;border-radius:999px;padding:12px 14px;background:linear-gradient(180deg,#f59e0b,#92400e);color:white;border:1px solid rgba(255,255,255,.35);font-weight:900;box-shadow:0 8px 24px rgba(0,0,0,.35)}';document.head.appendChild(st);var b=document.createElement('button');b.id='adminFloatBtn';b.innerHTML='🛠️ Admin';b.onclick=function(){window.acuarionexoActiveNav='Admin';try{localStorage.setItem('acuarionexo_active_nav','Admin')}catch(e){} adminPanel()};document.body.appendChild(b)}catch(e){}}
window.adminPanel=function(){
 if(!uid())return paint('<section class="premium-block"><h2>🛠️ Admin</h2><p>Inicia sesión para usar el panel admin.</p></section>');
 if(!adminEnabled())return paint('<section class="premium-block"><h2>🛠️ Activar Panel Admin</h2><p>Panel privado para preparar fichas, fotos, Gemini manual y publicación. No consume créditos IA.</p><button class="primary" onclick="AcuarioNexoAdmin.enable()">Activar admin en este dispositivo</button></section>');
 paint('<section class="premium-block"><div class="block-head"><h2>🛠️ Panel Admin</h2><button onclick="AcuarioNexoAdmin.disable()">Ocultar</button></div><p>Centro privado para preparar contenido sin gastar créditos IA.</p><div class="dashboard-grid"><article><h3>📷 Studio Fotos</h3><p>Prepara fotos con fondo limpio y miniaturas.</p><button onclick="adminStudioFotos()">Abrir</button></article><article><h3>📋 Fichas</h3><p>Borradores, revisión y publicadas.</p><button onclick="adminFichas()">Ver fichas</button></article><article><h3>✨ Importar Gemini</h3><p>Genera prompt, pega respuesta y valida ficha.</p><button onclick="adminGemini()">Importar</button></article><article><h3>🐞 Testers</h3><p>Reportes, fallos y seguimiento.</p><button onclick="adminTesters()">Ver</button></article></div></section>')
};
window.adminGemini=function(){var prompt='Crea una ficha tecnica completa para AcuarioNexo. Devuelve JSON con: marca, nombre, categoria, resumen_corto, ficha_tecnica, dosis, advertencias, compatibilidad, reef_safe, parametros_relacionados. No inventes datos criticos.';paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>✨ Importar Gemini gratis</h2><p>1. Copia este prompt en Gemini web gratis. 2. Pega aquí la respuesta JSON. 3. Guarda borrador.</p><label>Prompt</label><textarea id="admPrompt">'+E(prompt)+'</textarea><label>Respuesta Gemini JSON</label><textarea id="admJson"></textarea><button class="primary" onclick="adminImportGemini()">Importar respuesta</button><div id="admMsg"></div></section>')};
window.adminImportGemini=function(){try{var j=JSON.parse(admJson.value);sessionStorage.setItem('nexoadmin_import',JSON.stringify(j));admMsg.innerHTML='<div class="success">JSON válido. Abre Studio Fotos para completar foto y guardar.</div>'}catch(e){admMsg.innerHTML='<div class="error">JSON no válido: '+E(e.message)+'</div>'}};
window.adminFichas=async function(){paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>📋 Fichas</h2><div id="adminList">Cargando...</div></section>');try{var r=await window.s.from('nexoadmin_fichas').select('*').order('created_at',{ascending:false}).limit(30);if(r.error)throw r.error;var html=(r.data||[]).map(function(x){return '<article class="item"><h3>'+E((x.marca||'')+' '+(x.nombre||''))+'</h3><p><b>Estado:</b> '+E(x.estado)+' · <b>Publicado:</b> '+(x.publicado_en_app?'Sí':'No')+'</p><p>'+E((x.resumen_corto||x.ficha_tecnica||'').slice(0,180))+'</p><div class="grid2"><button onclick="adminPublish(\''+x.id+'\')">Publicar</button><button onclick="adminUnpublish(\''+x.id+'\')">Ocultar</button></div></article>'}).join('')||'<p class="notice">Sin fichas.</p>';document.getElementById('adminList').innerHTML=html}catch(e){document.getElementById('adminList').innerHTML='<div class="error">'+E(e.message)+'</div>'}};
window.adminPublish=async function(id){await window.s.from('nexoadmin_fichas').update({estado:'publicada',publicado_en_app:true,tester_visible:true,updated_at:new Date().toISOString()}).eq('id',id);adminFichas()};
window.adminUnpublish=async function(id){await window.s.from('nexoadmin_fichas').update({estado:'borrador',publicado_en_app:false,tester_visible:false,updated_at:new Date().toISOString()}).eq('id',id);adminFichas()};
window.adminTesters=function(){paint('<section class="premium-block"><button onclick="adminPanel()">← Admin</button><h2>🐞 Testers</h2><p class="notice">Preparado para reportes y seguimiento. Siguiente fase: tabla de fallos y actividad.</p></section>')};
window.AcuarioNexoAdmin.enable=enableAdmin;window.AcuarioNexoAdmin.disable=disableAdmin;
var old=window.goSection;window.goSection=function(n){if(n==='Admin')return adminPanel();return old?old(n):null};
setTimeout(injectAdminButton,900);setInterval(injectAdminButton,2000);
})();
