window.AcuarioNexoAdmin={version:'admin-session-aware-24-05'};
(function(){
function E(v){return String(v||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function app(){return document.getElementById('app')}
function paint(h){if(app())app().innerHTML=h;scrollTo(0,0)}
function enabled(){try{return localStorage.getItem('acuarionexo_admin_enabled')==='1'}catch(e){return false}}
async function currentUser(){if(window.u&&window.u.id)return window.u;try{var r=await window.s.auth.getSession();window.u=(r.data.session&&r.data.session.user)||null;return window.u}catch(e){return null}}
function addButton(){var box=document.querySelector('.top-actions');if(!box||document.getElementById('adminTopBtn'))return;var b=document.createElement('button');b.id='adminTopBtn';b.className='ghost';b.innerHTML='🛠️<small>Admin</small>';b.onclick=function(){adminPanel()};box.insertBefore(b,box.firstChild)}
window.adminPanel=async function(){var u=await currentUser();if(!u)return paint('<section class="card"><h2>Admin</h2><p>No hay sesión activa. Entra primero con tu correo y contraseña.</p><button class="primary" onclick="location.reload()">Volver a login</button></section>');if(!enabled())return paint('<section class="card"><h2>🛠️ Modo Admin</h2><p>Sesión detectada: '+E(u.email||'usuario')+'</p><p>Activa Admin en este dispositivo.</p><button class="primary" onclick="AcuarioNexoAdmin.enable()">Entrar como admin</button><button onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">Volver</button></section>');paint('<section class="card"><h2>🛠️ Panel Admin</h2><p>Usuarios, testers, permisos IA y consumo.</p><p><b>Sesión:</b> '+E(u.email||'usuario')+'</p><div class="grid"><button class="primary" onclick="adminUsers()">Usuarios / IA</button><button onclick="adminTesters()">Testers</button><button onclick="AcuarioNexoAdmin.disable()">Modo usuario</button></div></section>')};
window.adminUsers=async function(){paint('<section class="card"><button onclick="adminPanel()">← Admin</button><h2>Usuarios / IA</h2><div id="adminUsersBox">Cargando...</div></section>');try{var r=await window.s.from('user_ai_permissions').select('*').order('updated_at',{ascending:false}).limit(50);if(r.error)throw r.error;var rows=r.data||[];document.getElementById('adminUsersBox').innerHTML=rows.length?rows.map(function(x){return '<div class="item"><b>'+E(x.role)+'</b><p>'+E(x.user_id)+'</p><p>IA: '+(x.ai_enabled?'✅ Activada':'❌ Bloqueada')+'</p></div>'}).join(''):'<p class="notice">Sin usuarios registrados todavía.</p>'}catch(e){document.getElementById('adminUsersBox').innerHTML='<div class="error">'+E(e.message)+'</div>'}};
window.adminTesters=function(){paint('<section class="card"><button onclick="adminPanel()">← Admin</button><h2>Testers</h2><p class="notice">Aquí se verán testers, accesos, reportes y permisos.</p></section>')};
window.AcuarioNexoAdmin.enable=function(){try{localStorage.setItem('acuarionexo_admin_enabled','1')}catch(e){}adminPanel()};
window.AcuarioNexoAdmin.disable=function(){try{localStorage.removeItem('acuarionexo_admin_enabled')}catch(e){}adminPanel()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton);else addButton();setTimeout(addButton,800);setTimeout(addButton,2000);
})();