window.AcuarioNexoInventario={version:'inventario-clean-23-05-ia-v4-cache'};
(function(){
function E(v){return String(v||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function shortIAError(msg){msg=String(msg||'');if(msg.indexOf('Quota exceeded')>=0||msg.indexOf('quota')>=0)return '⚠️ Límite temporal de IA. No repitas muchas pruebas seguidas.';if(msg.indexOf('API key')>=0)return '⚠️ API key no válida. Revisa Supabase Secrets.';if(msg.indexOf('processing your request')>=0||msg.indexOf('request ID')>=0)return '⚠️ La IA rechazó esta imagen. Usa Ficha limpia y vuelve a probar.';if(msg.indexOf('Motor IA no cargado')>=0)return '⚠️ Motor IA no cargado. Refresca la app.';return '⚠️ IA no disponible: '+msg.slice(0,160)}
function uid(){return window.u&&window.u.id?window.u.id:'local'}
function key(){return 'an_inv_'+uid()}
function cacheKey(){return 'an_inv_ai_cache_'+uid()}
function get(){try{return JSON.parse(localStorage.getItem(key())||'[]')}catch(e){return []}}
function set(a){localStorage.setItem(key(),JSON.stringify(a))}
function getCache(){try{return JSON.parse(localStorage.getItem(cacheKey())||'{}')}catch(e){return {}}}
function setCache(c){try{localStorage.setItem(cacheKey(),JSON.stringify(c))}catch(e){}}
function bot(){return '<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Microfauna\')">🦠<small>Microfauna</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>'}
function menu(){window.acuarionexoActiveNav='Inventario';try{localStorage.setItem('acuarionexo_active_nav','Inventario')}catch(e){}return window.menu?window.menu():''}
function paint(h){document.getElementById('app').innerHTML=menu()+h+bot();scrollTo(0,0)}
function ficha(src,t){return window.fichaPremium?window.fichaPremium('prod',src||'',t||'Producto'):''}
function hash(s){var h=0;if(!s)return '0';for(var i=0;i<s.length;i+=97){h=((h<<5)-h+s.charCodeAt(i))|0}return String(Math.abs(h))+'_'+s.length}
function pick(obj,paths){for(var i=0;i<paths.length;i++){var p=paths[i].split('.'),v=obj;for(var j=0;j<p.length&&v!=null;j++)v=v[p[j]];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return ''}
function flatIA(d){d=d||{};var raw=d.raw||{},f=d.ficha||d.data||d.analysis||{},cam=d.campos||f.campos||raw.campos||{};return {marca:pick({d,raw,f,cam},['d.marca','f.marca','cam.marca','raw.marca','raw.ficha.marca','raw.data.marca','raw.campos.marca','raw.brand']),producto:pick({d,raw,f,cam},['d.producto','d.nombre','f.producto','f.nombre','cam.producto','cam.nombre','raw.producto','raw.nombre','raw.ficha.producto','raw.ficha.nombre','raw.data.producto','raw.data.nombre','raw.name']),categoria:pick({d,raw,f,cam},['d.categoria','f.categoria','cam.categoria','raw.categoria','raw.ficha.categoria','raw.data.categoria','raw.category','d.tipo','f.tipo']),uso:pick({d,raw,f,cam},['d.uso','f.uso','cam.uso','raw.uso','raw.ficha.uso','raw.data.uso','d.descripcion','f.descripcion']),dosis:pick({d,raw,f,cam},['d.dosis','f.dosis','cam.dosis','raw.dosis','raw.ficha.dosis','raw.data.dosis','d.dosis_marino','f.dosis_marino']),advertencias:pick({d,raw,f,cam},['d.advertencias','f.advertencias','cam.advertencias','raw.advertencias','raw.ficha.advertencias','raw.data.advertencias']),resumen:pick({d,raw,f,cam},['d.resumen_tecnico','f.resumen_tecnico','cam.resumen_tecnico','raw.resumen_tecnico','raw.ficha.resumen_tecnico','d.resumen_corto','f.resumen_corto']),confianza:pick({d,raw,f,cam},['d.confianza','f.confianza','cam.confianza','raw.confianza'])}}
function compressDataUrl(src,maxSide,quality){return new Promise(function(resolve){try{var img=new Image();img.onload=function(){var scale=Math.min(1,(maxSide||850)/Math.max(img.width,img.height));var w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));var c=document.createElement('canvas');c.width=w;c.height=h;var ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality||0.68))};img.onerror=function(){resolve(src)};img.src=src}catch(e){resolve(src)}})}
function applyIA(d){var x=flatIA(d);if(window.marca&&x.marca)marca.value=x.marca;if(window.nombre&&x.producto)nombre.value=x.producto;if(window.cat&&x.categoria)cat.value=x.categoria;if(window.dosis){var lines=[];if(x.uso)lines.push(x.uso);if(x.dosis)lines.push('Dosis: '+x.dosis);if(x.advertencias)lines.push('Advertencias: '+x.advertencias);if(x.resumen)lines.push('\nFicha técnica:\n'+x.resumen);dosis.value=lines.join('\n')||dosis.value}return x}
window.invClean=function(){var a=get();var html=a.length?a.map(function(x){return '<article class="item">'+ficha(x.clean,x.nombre)+'<h3>'+E((x.marca||'')+' '+(x.nombre||''))+'</h3><p><b>Categoría:</b> '+E(x.cat||'-')+' · <b>Stock:</b> '+E(x.cant||'-')+' · <b>Estado:</b> '+E(x.estado||'-')+'</p><p><b>Dosis/Ficha:</b> '+E((x.dosis||'-').slice(0,220))+'</p><div class="grid2"><button onclick="ivCleanForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="ivCleanDel(\''+x.id+'\')">Borrar</button></div></article>'}).join(''):'<p class="notice">Sin productos todavía.</p>';paint('<section class="premium-block"><h2>📦 Inventario IA</h2><p>Sube foto, recorta, analiza una sola vez y guarda. La app reutiliza caché para no gastar IA repitiendo.</p><button class="primary" onclick="ivCleanForm()">+ Añadir producto</button></section><section class="premium-block"><h2>Productos</h2>'+html+'</section>')};
window.ivCleanForm=function(id){var a=get();var x=a.find(function(r){return r.id===id})||{};paint('<section class="premium-block"><button onclick="goSection(\'Inventario\')">← Volver</button><h2>Producto</h2><label>Foto</label><input type="file" accept="image/*" onchange="ivCleanPhoto(this)"><input id="foto_original" type="hidden" value="'+E(x.original||'')+'"><input id="foto_limpia" type="hidden" value="'+E(x.clean||'')+'"><input id="ia_raw" type="hidden" value="'+E(x.ia_raw?JSON.stringify(x.ia_raw):'')+'"><div id="foto_limpia_preview">'+ficha(x.clean,'Producto')+'</div><div class="grid2"><button id="btnIA" onclick="ivCleanAI()">🧠 Analizar con IA</button><button onclick="anMakeClean&&anMakeClean()">✨ Ficha limpia</button></div><div id="ia_status" class="small">Primero deja bien la ficha limpia. Después pulsa IA solo una vez.</div><label>Marca</label><input id="marca" value="'+E(x.marca||'')+'"><label>Producto</label><input id="nombre" value="'+E(x.nombre||'')+'"><label>Categoría</label><input id="cat" value="'+E(x.cat||'')+'"><label>Dosis / ficha técnica</label><textarea id="dosis">'+E(x.dosis||'')+'</textarea><label>Cantidad</label><input id="cant" value="'+E(x.cant||'')+'"><label>Estado</label><input id="estado" value="'+E(x.estado||'Correcto')+'"><button class="primary" onclick="ivCleanSave(\''+(id||'')+'\')">Guardar ficha</button></section>')};
window.ivCleanPhoto=function(inp){var f=inp.files&&inp.files[0];if(!f)return;var st=document.getElementById('ia_status');if(st)st.innerHTML='📷 Cargando foto. Pulsa ✨ Ficha limpia antes de IA.';var r=new FileReader();r.onload=function(e){foto_original.value=e.target.result;foto_limpia.value=e.target.result;foto_limpia_preview.innerHTML=ficha(e.target.result,'Producto')};r.readAsDataURL(f)};
window.ivCleanAI=async function(){var st=document.getElementById('ia_status'),btn=document.getElementById('btnIA');try{if(btn)btn.disabled=true;if(st)st.innerHTML='🧠 Preparando imagen comprimida...';if(!window.AcuarioNexoGemini)throw new Error('Motor IA no cargado');var base=(window.foto_limpia&&foto_limpia.value)||(window.foto_original&&foto_original.value)||'';if(!base)throw new Error('Primero añade una foto');var img=await compressDataUrl(base,760,0.62);var h=hash(img);var c=getCache();var d=c[h];if(d){if(st)st.innerHTML='✅ IA recuperada de caché. No se ha gastado crédito.'}else{if(st)st.innerHTML='🧠 Analizando con IA. No cierres la pantalla...';d=await window.AcuarioNexoGemini.analyse('inventario',img,'Rellena ficha de inventario completa pero concisa.');c[h]=d;setCache(c)}if(window.ia_raw)ia_raw.value=JSON.stringify(d);var x=applyIA(d);if(st)st.innerHTML='✅ IA completada'+(x.confianza?' · confianza '+x.confianza:'')+'. Revisa y pulsa Guardar ficha.'}catch(e){if(st)st.innerHTML=shortIAError(e.message)}finally{if(btn)btn.disabled=false}}
window.ivCleanSave=function(id){var a=get();var raw={};try{raw=ia_raw.value?JSON.parse(ia_raw.value):{}}catch(e){}var row={id:id||Date.now().toString(),original:foto_original.value,clean:foto_limpia.value,marca:marca.value,nombre:nombre.value||'Sin nombre',cat:cat.value,dosis:dosis.value,cant:cant.value,estado:estado.value,ia_raw:raw,updated_at:new Date().toISOString()};var i=a.findIndex(function(x){return x.id===row.id});if(i>=0)a[i]=row;else a.unshift(row);set(a);invClean()};
window.ivCleanDel=function(id){set(get().filter(function(x){return x.id!==id}));invClean()};
var old=window.goSection;window.goSection=function(n){if(n==='Inventario')return invClean();return old?old(n):null};
window.inventario=window.invClean;
})();
