/* AcuarioNexo · Inventario global */
(function(){
 const cats=['Sal','Medicamento','Bacteria','Comida','Test','Aditivo','Consumible','Recambio','Equipamiento'];
 function h(x){return (window.E?window.E(x):String(x||''))}
 function v(id){return document.getElementById(id)?.value?.trim()||''}
 function n(id){const x=v(id);return x===''?null:Number(x)}
 function st(i){const q=Number(i.quantity||0),m=Number(i.min_stock||0);const exp=i.expiry_date?Math.ceil((new Date(i.expiry_date)-Date.now())/86400000):99999;if(exp<0)return ['error','Caducado'];if(exp<30)return ['notice','Caduca pronto'];if(m&&q<=m)return ['notice','Stock bajo'];return ['success','OK']}
 function card(i){const a=st(i);return `<div class="item"><span class="${a[0]}">${h(a[1])}</span><h3>${h(i.name)}</h3><p class="small">${h(i.category||'Producto')} · ${h(i.brand||'')}</p><p><b>${h(i.quantity??'-')} ${h(i.unit||'')}</b> · mínimo ${h(i.min_stock??'-')}</p><p>Caducidad: <b>${h(i.expiry_date||'Sin fecha')}</b></p>${i.notes?`<p>${h(i.notes)}</p>`:''}</div>`}
 async function items(){const r=await window.s.from('inventory_items').select('*').eq('user_id',window.u.id).order('created_at',{ascending:false}).limit(300);if(r.error)throw r.error;return r.data||[]}
 window.inventario=async function(){if(!window.u)return window.login();try{window.S(`<section class="panel"><h2>Inventario global</h2>${window.M('Cargando inventario...')}</section>`,'inicio');const data=await items();const avisos=data.filter(x=>st(x)[1]!=='OK').length;window.S(`<section class="summary-card"><div><small>Almacén global</small><h2>Inventario</h2><p>${data.length} productos · ${avisos} avisos</p></div><button onclick="formInventarioGlobal()">+</button></section><section class="panel"><div class="panel-head"><h2>Stock, caducidades y compras</h2><button onclick="formInventarioGlobal()">Añadir</button></div><p class="small">Inventario común para todos tus acuarios. La IA decidirá después qué producto sirve para cada acuario, cambio de agua, enfermedad o parámetro.</p><div class="quick-actions"><button onclick="formInventarioGlobal('Sal')">🧂 Sal</button><button onclick="formInventarioGlobal('Medicamento')">💊 Medicamento</button><button onclick="formInventarioGlobal('Bacteria')">🦠 Bacteria</button><button onclick="formInventarioGlobal('Comida')">🍤 Comida</button><button onclick="formInventarioGlobal('Test')">🧪 Test</button><button onclick="formInventarioGlobal('Aditivo')">⚗️ Aditivo</button></div>${data.map(card).join('')||window.M('Sin productos todavía.')}</section><div style="height:140px"></div>`,'inicio')}catch(e){window.S(`<section class="panel"><h2>Inventario global</h2>${window.M(e.message,'error')}</section>`,'inicio')}}
 window.formInventarioGlobal=function(cat=''){window.S(`<section class="panel"><button onclick="inventario()">← Volver</button><h2>Añadir producto global</h2><label>Categoría</label><select id="invCat">${cats.map(c=>`<option ${c===cat?'selected':''}>${c}</option>`).join('')}</select><label>Nombre</label><input id="invName"><label>Marca</label><input id="invBrand"><label>Cantidad</label><input id="invQty" type="number" step="0.01"><label>Unidad</label><input id="invUnit" placeholder="kg, g, ml, unidades"><label>Stock mínimo</label><input id="invMin" type="number" step="0.01"><label>Caducidad</label><input id="invExp" type="date"><label>Notas para IA</label><textarea id="invNotes" placeholder="Para marino, reef, dulce, hospital, dosis, uso, compatibilidades..."></textarea><button class="primary" onclick="saveInventarioGlobal()">Guardar</button><div id="x"></div></section><div style="height:140px"></div>`,'inicio')}
 window.saveInventarioGlobal=async function(){try{if(!v('invName'))throw new Error('Pon el nombre del producto.');const row={user_id:window.u.id,name:v('invName'),brand:v('invBrand')||null,category:v('invCat'),quantity:n('invQty'),unit:v('invUnit')||null,min_stock:n('invMin'),expiry_date:v('invExp')||null,notes:v('invNotes')||null,ai_review_status:'manual'};const r=await window.s.from('inventory_items').insert(row);if(r.error)throw r.error;inventario()}catch(e){document.getElementById('x').innerHTML=window.M(e.message,'error')}}
})();