window.AcuarioNexoInventario={version:'inventario-clean-23-05-ia-v3'};
(function(){
function E(v){return String(v||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function shortIAError(msg){msg=String(msg||'');if(msg.indexOf('Quota exceeded')>=0||msg.indexOf('quota')>=0){var m=msg.match(/retry in\s*([0-9.]+)s/i);return '⚠️ Límite temporal de Gemini alcanzado'+(m?' · reintenta en '+Math.ceil(Number(m[1]))+' segundos.':'')+' Si sigue saliendo, la cuenta/proyecto no tiene cuota gratuita activa.'}if(msg.indexOf('API key not valid')>=0)return '⚠️ API key no válida. Revisa Supabase Secrets.';if(msg.indexOf('processing your request')>=0||msg.indexOf('request ID')>=0)return '⚠️ OpenAI rechazó esta imagen. He preparado el envío comprimido; refresca la app y vuelve a probar con la ficha limpia.';if(msg.indexOf('Motor IA no cargado')>=0)return '⚠️ Motor IA no cargado. Refresca la app.';return '⚠️ IA no disponible: '+msg.slice(0,160)}
function uid(){return window.u&&window.u.id?window.u.id:'local'}
function key(){return 'an_inv_'+uid()}
function get(){try{return JSON.parse(localStorage.getItem(key())||'[]')}catch(e){return []}}
function set(a){localStorage.setItem(key(),JSON.stringify(a))}
function bot(){return '<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Microfauna\')">🦠<small>Microfauna</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>'}
function menu(){window.acuarionexoActiveNav='Inventario';localStorage.setItem('acuarionexo_active_nav','Inventario');return window.menu?window.menu():''}
function paint(h){document.getElementById('app').innerHTML=menu()+h+bot();scrollTo(0,0)}
function ficha(src,t){return window.fichaPremium?window.fichaPremium('prod',src||'',t||'Producto'):''}
function compressDataUrl(src,maxSide,quality){return new Promise(function(resolve){try{var img=new Image();img.onload=function(){var scale=Math.min(1,(maxSide||900)/Math.max(img.width,img.height));var w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));var c=document.createElement('canvas');c.width=w;c.height=h;var ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality||0.72))};img.onerror=function(){resolve(src)};img.src=src}catch(e){resolve(src)}})}
window.invClean=function(){var a=get();var html=a.length?a.map(function(x){return '<article class="item">'+ficha(x.clean,x.nombre)+'<h3>'+E(x.marca)+' '+E(x.nombre)+'</h3><p><b>Categoría:</b> '+E(x.cat||'-')+' · <b>Stock:</b> '+E(x.cant||'-')+' · <b>Estado:</b> '+E(x.estado||'-')+'</p><p><b>Dosis:</b> '+E(x.dosis||'-')+'</p><div class="grid2"><button onclick="ivCleanForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="ivCleanDel(\''+x.id+'\')">Borrar</button></div></article>'}).join(''):'<p class="notice">Sin productos todavía.</p>';paint('<section class="premium-block"><h2>📦 Inventario IA</h2><p>Motor limpio: ficha visual única y datos separados.</p><button class="primary" onclick="ivCleanForm()">+ Añadir producto</button></section><section class="premium-block"><h2>Productos</h2>'+html+'</section>')};
window.ivCleanForm=function(id){var a=get();var x=a.find(function(r){return r.id===id})||{};paint('<section class="premium-block"><button onclick="goSection(\'Inventario\')">← Volver</button><h2>Producto</h2><label>Foto</label><input type="file" accept="image/*" onchange="ivCleanPhoto(this)"><input id="foto_original" type="hidden" value="'+E(x.original||'')+'"><input id="foto_limpia" type="hidden" value="'+E(x.clean||'')+'"><div id="foto_limpia_preview">'+ficha(x.clean,'Producto')+'</div><div class="grid2"><button onclick="ivCleanAI()">🧠 Analizar con IA</button><button onclick="anMakeClean&&anMakeClean()">✨ Ficha limpia</button></div><div id="ia_status" class="small"></div><label>Marca</label><input id="marca" value="'+E(x.marca||'')+'"><label>Producto</label><input id="nombre" value="'+E(x.nombre||'')+'"><label>Categoría</label><input id="cat" value="'+E(x.cat||'')+'"><label>Dosis</label><textarea id="dosis">'+E(x.dosis||'')+'</textarea><label>Cantidad</label><input id="cant" value="'+E(x.cant||'')+'"><label>Estado</label><input id="estado" value="'+E(x.estado||'Correcto')+'"><button class="primary" onclick="ivCleanSave(\''+(id||'')+'\')">Guardar</button></section>')};
window.ivCleanPhoto=function(inp){var f=inp.files&&inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){foto_original.value=e.target.result;foto_limpia.value=e.target.result;foto_limpia_preview.innerHTML=ficha(e.target.result,'Producto')};r.readAsDataURL(f)};
window.ivCleanAI=async function(){var st=document.getElementById('ia_status');try{if(st)st.innerHTML='🧠 Preparando imagen limpia...';if(!window.AcuarioNexoGemini)throw new Error('Motor IA no cargado');var base=(window.foto_limpia&&foto_limpia.value)||(window.foto_original&&foto_original.value)||'';if(!base)throw new Error('Primero añade una foto');if(window.anMakeClean&&window.foto_limpia&&foto_limpia.value===foto_original.value){try{window.anMakeClean()}catch(_){}}var img=await compressDataUrl((window.foto_limpia&&foto_limpia.value)||base,850,0.68);if(st)st.innerHTML='🧠 Analizando con IA...';var d=await window.AcuarioNexoGemini.analyse('inventario',img);if(window.marca)marca.value=d.marca||marca.value;if(window.nombre)nombre.value=d.producto||nombre.value;if(window.cat)cat.value=d.categoria||cat.value;if(window.dosis)dosis.value=((d.uso||'')+(d.dosis?'\nDosis: '+d.dosis:'')+(d.advertencias?'\nAdvertencias: '+d.advertencias:'')+(d.resumen_tecnico?'\n\nFicha técnica:\n'+d.resumen_tecnico:''));if(st)st.innerHTML='✅ IA completada. Revisa antes de guardar.'}catch(e){if(st)st.innerHTML=shortIAError(e.message)}}
window.ivCleanSave=function(id){var a=get();var row={id:id||Date.now().toString(),original:foto_original.value,clean:foto_limpia.value,marca:marca.value,nombre:nombre.value||'Sin nombre',cat:cat.value,dosis:dosis.value,cant:cant.value,estado:estado.value};var i=a.findIndex(function(x){return x.id===row.id});if(i>=0)a[i]=row;else a.unshift(row);set(a);invClean()};
window.ivCleanDel=function(id){set(get().filter(function(x){return x.id!==id}));invClean()};
var old=window.goSection;window.goSection=function(n){if(n==='Inventario')return invClean();return old?old(n):null};
window.inventario=window.invClean;
})();
