(function(){
const E=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const K=n=>'an_'+n+'_'+(window.u?.id||'local');
const G=n=>{try{return JSON.parse(localStorage.getItem(K(n))||'[]')}catch(e){return[]}};
const W=(n,v)=>localStorage.setItem(K(n),JSON.stringify(v));
const B=()=>'<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Microfauna\')">🦠<small>Microfauna</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>';
function N(n){window.acuarionexoActiveNav=n;localStorage.setItem('acuarionexo_active_nav',n);return window.menu?window.menu():''}
function R(n,h){document.getElementById('app').innerHTML=N(n)+h+B();scrollTo(0,0);setTimeout(()=>document.querySelector('.premium-scroll .nav-active')?.scrollIntoView({inline:'center',block:'nearest'}),80)}
function ficha(tipo,src,tit){let c={producto:'#0e7890',pez:'#0e7890',coral:'#8b5cf6',micro:'#84cc16',inv:'#f59e0b'}[tipo]||'#0e7890';let sub=tipo==='pez'?'FONDO OFICIAL PARA FICHAS DE PECES':'FONDO OFICIAL PARA FICHAS';return '<div style="background:#f7f6f0;color:#102033;border-radius:20px;padding:12px;margin:10px 0;box-shadow:0 8px 26px #0004;overflow:hidden"><div style="position:relative;background:linear-gradient(180deg,#fbfaf5,#f4f1ea);border-radius:16px;padding:18px 12px 12px;min-height:520px"><div style="position:absolute;left:10px;top:8px;width:120px;height:95px;background:radial-gradient(circle,#9bd3df 2px,transparent 3px);background-size:14px 14px;opacity:.45"></div><div style="position:absolute;right:18px;top:16px;color:'+c+';opacity:.18;font-size:44px;line-height:.62;font-weight:900">≋<br>≋<br>≋</div><div style="text-align:center;position:relative;z-index:2;margin-top:2px"><div style="font-weight:950;font-size:31px;letter-spacing:2px;color:#132238">ACUARIO<span style="color:'+c+'">NEXO</span></div><div style="font-size:12px;letter-spacing:1.2px;font-weight:800;color:#1b2c3f">'+sub+'</div></div><div style="position:absolute;left:-38px;top:170px;color:'+c+';opacity:.13;font-size:190px;transform:rotate(-12deg)">♒</div><div style="position:absolute;right:-38px;top:190px;color:'+c+';opacity:.13;font-size:185px;transform:rotate(12deg)">♒</div><div style="height:310px;display:flex;align-items:center;justify-content:center;position:relative;z-index:2;margin-top:20px">'+(src?'<img src="'+src+'" style="max-width:86%;max-height:292px;object-fit:contain;filter:drop-shadow(0 14px 12px rgba(0,0,0,.16))">':'<span style="color:#8a98a6;font-weight:900">Fondo oficial sin sujeto</span>')+'</div><div style="height:1px;background:'+c+';opacity:.45;margin:4px 38px 14px"></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:4px;text-align:center;color:#19324a;font-size:10.5px;font-weight:800"><span>📷<br>FONDO<br>UNIFORME</span><span>🐠<br>COLOR<br>REAL</span><span>🛡️<br>SIN ELEMENTOS<br>EXTRA</span><span>✨<br>ILUMINACIÓN<br>NATURAL</span></div><div style="height:1px;background:'+c+';opacity:.35;margin:14px 38px 8px"></div><div style="text-align:center;font-size:15px;font-weight:900;color:'+c+'">acuarionexo.app</div></div></div>'}
function readPhoto(inp,target){let f=inp.files&&inp.files[0];if(!f)return;let r=new FileReader();r.onload=e=>{let v=document.getElementById(target);if(v)v.value=e.target.result;let s=document.getElementById(target+'_status');if(s)s.innerHTML='✅ Foto cargada para IA';let p=document.getElementById('foto_limpia_preview');if(p)p.innerHTML=ficha('producto',e.target.result,'Producto recortado/centrado')};r.readAsDataURL(f)}
window.anReadPhoto=readPhoto;
window.anMakeClean=function(){let src=document.getElementById('foto_original')?.value||'';document.getElementById('foto_limpia').value=src;document.getElementById('foto_limpia_preview').innerHTML=ficha('producto',src,'Producto recortado/centrado')};
function micro(){let a=G('micro');R('Microfauna','<section class="premium-block"><h2>🦠 Microfauna</h2><p>Cultivos de fito, copépodos, rotíferos, artemia e infusorios.</p><button class="primary" onclick="mfForm()">+ Nuevo cultivo</button></section><section class="premium-block"><h2>Cultivos</h2>'+(a.length?a.map(x=>'<article class="item"><h3>'+E(x.tipo)+' · '+E(x.nombre)+'</h3><p>'+E(x.estado)+' · '+E(x.fecha||'-')+'</p><p>'+E(x.notas||'')+'</p><div class="grid2"><button onclick="mfForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="mfDel(\''+x.id+'\')">Borrar</button></div></article>').join(''):'<p class="notice">Sin cultivos todavía.</p>')+'</section>')}
window.mfForm=function(id){let a=G('micro'),x=a.find(i=>i.id===id)||{};R('Microfauna','<section class="premium-block"><button onclick="goSection(\'Microfauna\')">← Volver</button><h2>Cultivo</h2><label>Tipo</label><select id="t"><option>Fitoplancton</option><option>Copépodos</option><option>Rotíferos</option><option>Artemia</option><option>Infusorios</option></select><label>Nombre</label><input id="n" value="'+E(x.nombre||'')+'"><label>Estado</label><select id="e"><option>Activo</option><option>Vigilar</option><option>Parado</option></select><label>Fecha</label><input id="f" type="date" value="'+E(x.fecha||'')+'"><label>Notas</label><textarea id="no">'+E(x.notas||'')+'</textarea><button class="primary" onclick="mfSave(\''+(id||'')+'\')">Guardar</button></section>');if(x.tipo)t.value=x.tipo;if(x.estado)e.value=x.estado};
window.mfSave=function(id){let a=G('micro'),r={id:id||Date.now().toString(),tipo:t.value,nombre:n.value||'Sin nombre',estado:e.value,fecha:f.value,notas:no.value};let i=a.findIndex(x=>x.id===r.id);i>=0?a[i]=r:a.unshift(r);W('micro',a);micro()};window.mfDel=id=>{W('micro',G('micro').filter(x=>x.id!==id));micro()};
function inv(){let a=G('inv');R('Inventario','<section class="premium-block"><h2>📦 Inventario IA</h2><p>La foto original queda guardada para IA, pero no ocupa espacio. La ficha muestra solo la imagen limpia.</p><div class="grid2"><button class="primary" onclick="ivForm()">+ Añadir producto</button><button onclick="ivScan()">📷 Escanear con IA</button></div></section><section class="premium-block"><h2>Productos</h2>'+(a.length?a.map(x=>'<article class="item">'+(x.clean?ficha('producto',x.clean,x.nombre):'')+'<h3>'+E(x.marca||'')+' '+E(x.nombre)+'</h3><p><b>Categoría:</b> '+E(x.cat)+' · <b>Stock:</b> '+E(x.cant||'-')+' · <b>Estado:</b> '+E(x.estado)+'</p><p><b>Dosis:</b> '+E(x.dosis||'-')+'</p><p><b>Cliente:</b> compra '+E(x.compra||'-')+' · caducidad '+E(x.cad||'-')+' · '+E(x.precio||'-')+' · '+E(x.tienda||'-')+'</p><div class="grid2"><button onclick="ivForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="ivDel(\''+x.id+'\')">Borrar</button></div></article>').join(''):'<p class="notice">Sin productos todavía.</p>')+'</section>')}
window.ivScan=function(){R('Inventario','<section class="premium-block"><button onclick="goSection(\'Inventario\')">← Volver</button><h2>📷 Escanear producto con IA</h2><p class="notice">Elige cámara o galería. La foto original se guarda para IA sin mostrarse grande en la app.</p><div class="grid2"><label>📷 Sacar foto<input type="file" accept="image/*" capture="environment" onchange="anReadPhoto(this,\'scan_photo\')"></label><label>🖼️ Elegir de galería<input type="file" accept="image/*" onchange="anReadPhoto(this,\'scan_photo\')"></label></div><input id="scan_photo" type="hidden"><div id="scan_photo_status"></div><button class="primary" onclick="ivForm()">Crear ficha manual</button></section>')};
window.ivForm=function(id){let a=G('inv'),x=a.find(i=>i.id===id)||{};R('Inventario','<section class="premium-block"><button onclick="goSection(\'Inventario\')">← Volver</button><h2>Producto</h2><h3>📷 Foto para IA</h3><p class="small">La original se guarda oculta. En la app se verá la ficha limpia.</p><div class="grid2"><label>📷 Sacar foto<input type="file" accept="image/*" capture="environment" onchange="anReadPhoto(this,\'foto_original\')"></label><label>🖼️ Galería<input type="file" accept="image/*" onchange="anReadPhoto(this,\'foto_original\')"></label></div><input id="foto_original" type="hidden" value="'+E(x.original||'')+'"><input id="foto_limpia" type="hidden" value="'+E(x.clean||'')+'"><div id="foto_original_status">'+(x.original?'✅ Foto original guardada para IA':'')+'</div><button onclick="anMakeClean()">✨ Generar ficha limpia</button><h3>Ficha limpia</h3><div id="foto_limpia_preview">'+(x.clean?ficha('producto',x.clean,x.nombre):ficha('producto',''))+'</div><h3>🧠 Ficha técnica IA</h3><label>Marca</label><input id="marca" value="'+E(x.marca||'')+'"><label>Producto</label><input id="inm" value="'+E(x.nombre||'')+'"><label>Categoría</label><select id="cat"><option>Comida</option><option>Sal</option><option>Aditivo</option><option>Medicación</option><option>Test</option><option>Repuesto</option><option>Equipo</option><option>Otro</option></select><label>Dosis / cálculo por litros</label><textarea id="dosis">'+E(x.dosis||'')+'</textarea><h3>👤 Datos del cliente</h3><label>Cantidad disponible</label><input id="cant" value="'+E(x.cant||'')+'"><label>Estado stock</label><select id="est"><option>Correcto</option><option>Bajo</option><option>Agotado</option><option>Caducado</option></select><label>Fecha compra</label><input id="compra" type="date" value="'+E(x.compra||'')+'"><label>Caducidad</label><input id="cad" type="date" value="'+E(x.cad||'')+'"><label>Precio</label><input id="precio" value="'+E(x.precio||'')+'"><label>Tienda</label><input id="tienda" value="'+E(x.tienda||'')+'"><button class="primary" onclick="ivSave(\''+(id||'')+'\')">Guardar producto</button></section>');if(x.cat)cat.value=x.cat;if(x.estado)est.value=x.estado};
window.ivSave=function(id){let a=G('inv'),r={id:id||Date.now().toString(),original:foto_original.value,clean:foto_limpia.value||foto_original.value,marca:marca.value,nombre:inm.value||'Sin nombre',cat:cat.value,dosis:dosis.value,cant:cant.value,estado:est.value,compra:compra.value,cad:cad.value,precio:precio.value,tienda:tienda.value};let i=a.findIndex(x=>x.id===r.id);i>=0?a[i]=r:a.unshift(r);W('inv',a);inv()};window.ivDel=id=>{W('inv',G('inv').filter(x=>x.id!==id));inv()};
const old=window.goSection;window.goSection=function(n){if(n==='Microfauna')return micro();if(n==='Inventario')return inv();return old?old(n):null};window.microfauna=micro;window.inventario=inv;
})();