(function(){
const E=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const K=n=>'an_'+n+'_'+(window.u?.id||'local');
const G=n=>{try{return JSON.parse(localStorage.getItem(K(n))||'[]')}catch(e){return[]}};
const W=(n,v)=>localStorage.setItem(K(n),JSON.stringify(v));
const B=()=>'<nav class="bottom-nav"><button onclick="goSection(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="goSection(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="goSection(\'Microfauna\')">🦠<small>Microfauna</small></button><button onclick="goSection(\'Inventario\')">📦<small>Inventario</small></button><button onclick="goSection(\'IA\')">🧠<small>IA</small></button></nav>';
function N(n){window.acuarionexoActiveNav=n;localStorage.setItem('acuarionexo_active_nav',n);return window.menu?window.menu():''}
function R(n,h){document.getElementById('app').innerHTML=N(n)+h+B();scrollTo(0,0);setTimeout(()=>document.querySelector('.premium-scroll .nav-active')?.scrollIntoView({inline:'center',block:'nearest'}),80)}
function micro(){let a=G('micro');R('Microfauna','<section class="premium-block"><h2>🦠 Microfauna</h2><p>Cultivos de fito, copepodos, rotiferos, artemia e infusorios.</p><button class="primary" onclick="mfForm()">+ Nuevo cultivo</button></section><section class="premium-block"><h2>Cultivos</h2>'+(a.length?a.map(x=>'<article class="item"><h3>'+E(x.tipo)+' · '+E(x.nombre)+'</h3><p>'+E(x.estado)+' · '+E(x.fecha||'-')+'</p><p>'+E(x.notas||'')+'</p><div class="grid2"><button onclick="mfForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="mfDel(\''+x.id+'\')">Borrar</button></div></article>').join(''):'<p class="notice">Sin cultivos todavía.</p>')+'</section>')}
window.mfForm=function(id){let a=G('micro'),x=a.find(i=>i.id===id)||{};R('Microfauna','<section class="premium-block"><button onclick="goSection(\'Microfauna\')">← Volver</button><h2>Cultivo</h2><label>Tipo</label><select id="t"><option>Fitoplancton</option><option>Copepodos</option><option>Rotiferos</option><option>Artemia</option><option>Infusorios</option></select><label>Nombre</label><input id="n" value="'+E(x.nombre||'')+'"><label>Estado</label><select id="e"><option>Activo</option><option>Vigilar</option><option>Parado</option></select><label>Fecha</label><input id="f" type="date" value="'+E(x.fecha||'')+'"><label>Notas</label><textarea id="no">'+E(x.notas||'')+'</textarea><button class="primary" onclick="mfSave(\''+(id||'')+'\')">Guardar</button></section>'); if(x.tipo)t.value=x.tipo;if(x.estado)e.value=x.estado};
window.mfSave=function(id){let a=G('micro'),r={id:id||Date.now().toString(),tipo:t.value,nombre:n.value||'Sin nombre',estado:e.value,fecha:f.value,notas:no.value};let i=a.findIndex(x=>x.id===r.id);i>=0?a[i]=r:a.unshift(r);W('micro',a);micro()};
window.mfDel=function(id){W('micro',G('micro').filter(x=>x.id!==id));micro()};
function inv(){let a=G('inv');R('Inventario','<section class="premium-block"><h2>📦 Inventario</h2><p>Stock, comida, sal, test, repuestos, compras y garantías.</p><button class="primary" onclick="ivForm()">+ Nuevo artículo</button></section><section class="premium-block"><h2>Artículos</h2>'+(a.length?a.map(x=>'<article class="item"><h3>'+E(x.nombre)+'</h3><p>'+E(x.cat)+' · '+E(x.cant||'-')+' · '+E(x.estado)+'</p><p>'+E(x.notas||'')+'</p><div class="grid2"><button onclick="ivForm(\''+x.id+'\')">Editar</button><button class="danger" onclick="ivDel(\''+x.id+'\')">Borrar</button></div></article>').join(''):'<p class="notice">Sin artículos todavía.</p>')+'</section>')}
window.ivForm=function(id){let a=G('inv'),x=a.find(i=>i.id===id)||{};R('Inventario','<section class="premium-block"><button onclick="goSection(\'Inventario\')">← Volver</button><h2>Artículo</h2><label>Nombre</label><input id="inm" value="'+E(x.nombre||'')+'"><label>Categoría</label><select id="cat"><option>Comida</option><option>Sal</option><option>Test</option><option>Repuesto</option><option>Equipo</option><option>Otro</option></select><label>Cantidad</label><input id="cant" value="'+E(x.cant||'')+'"><label>Estado</label><select id="est"><option>Correcto</option><option>Bajo</option><option>Agotado</option></select><label>Notas</label><textarea id="ino">'+E(x.notas||'')+'</textarea><button class="primary" onclick="ivSave(\''+(id||'')+'\')">Guardar</button></section>');if(x.cat)cat.value=x.cat;if(x.estado)est.value=x.estado};
window.ivSave=function(id){let a=G('inv'),r={id:id||Date.now().toString(),nombre:inm.value||'Sin nombre',cat:cat.value,cant:cant.value,estado:est.value,notas:ino.value};let i=a.findIndex(x=>x.id===r.id);i>=0?a[i]=r:a.unshift(r);W('inv',a);inv()};
window.ivDel=function(id){W('inv',G('inv').filter(x=>x.id!==id));inv()};
const old=window.goSection;window.goSection=function(n){if(n==='Microfauna')return micro();if(n==='Inventario')return inv();return old?old(n):null};window.microfauna=micro;window.inventario=inv;
})();