window.AcuarioNexoNavigation={version:'core-active-buttons-24-05'};
(function(){
function E(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function A(){return document.getElementById('app')}
function set(n){window.acuarionexoActiveNav=n;try{localStorage.setItem('acuarionexo_active_nav',n)}catch(e){}}
function current(){return window.acuarionexoActiveNav||localStorage.getItem('acuarionexo_active_nav')||'Dashboard'}
function norm(n){return n==='Inicio'?'Dashboard':n}
function top(){var act=norm(current());var b=[['🏠','Dashboard'],['🐠','Acuarios'],['🧪','Parámetros'],['🐟','Animales'],['📷','Fotos'],['🔔','Avisos']];return '<section class="premium-nav"><div class="premium-scroll">'+b.map(function(x){var on=act===x[1]?' nav-active active':'';return '<button class="'+on+'" onclick="AcuarioNexoNavigation.safeGo(\''+x[1]+'\')"><span>'+x[0]+'</span><small>'+x[1]+'</small></button>'}).join('')+'</div></section>'}
function bottom(){var act=norm(current());function c(n){return act===n?' class="bottom-active active"':''}return '<nav class="bottom-nav"><button'+c('Dashboard')+' onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">🏠<small>Inicio</small></button><button'+c('Acuarios')+' onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="formA&&formA()">＋<small>Añadir</small></button><button'+c('Parámetros')+' onclick="AcuarioNexoNavigation.safeGo(\'Parámetros\')">🧪<small>Parámetros</small></button><button'+c('IA')+' onclick="AcuarioNexoNavigation.safeGo(\'IA\')">🧠<small>IA</small></button></nav>'}
function style(){if(document.getElementById('activeNavStyle'))return;var s=document.createElement('style');s.id='activeNavStyle';s.textContent='.premium-scroll button.nav-active,.premium-scroll button.active{background:linear-gradient(135deg,#0877ff,#0bbcff)!important;border-color:rgba(186,235,255,.85)!important;color:#fff!important;box-shadow:0 0 0 1px rgba(255,255,255,.18),0 10px 24px rgba(8,119,255,.28)!important;transform:translateY(-1px)}.bottom-nav button.bottom-active,.bottom-nav button.active{background:linear-gradient(135deg,#0877ff,#0bbcff)!important;color:#fff!important;border-color:rgba(186,235,255,.75)!important;box-shadow:0 -2px 18px rgba(8,119,255,.28)!important}.premium-scroll button:active,.bottom-nav button:active{transform:scale(.96)!important;filter:brightness(1.15)}';document.head.appendChild(s)}
function render(n,h,nav){set(n);style();var a=A();if(!a)return;a.innerHTML=(nav===false?'':top())+h+(nav===false?'':bottom());scrollTo(0,0)}
function login(){var b=document.getElementById('logoutBtn');if(b)b.classList.add('hidden');if(typeof window.login==='function')return window.login();render('Login','<section class="card"><h2>Entrar</h2><input id="em" placeholder="Email"><input id="pw" type="password" placeholder="Contraseña"><button class="primary" onclick="iniciar&&iniciar()">Entrar</button><button onclick="crear&&crear()">Crear cuenta</button><div id="x"></div></section>',false)}
async function user(){if(!window.s)return null;try{var r=await window.s.auth.getSession();window.u=(r.data.session&&r.data.session.user)||null;var b=document.getElementById('logoutBtn');if(b){b.classList.toggle('hidden',!window.u);b.onclick=async function(){try{await window.s.auth.signOut()}catch(e){}try{localStorage.clear()}catch(e){}location.replace(location.pathname+'?v='+Date.now())}}return window.u}catch(e){window.u=null;return null}}
async function need(){var u=await user();if(!u)login();return u}
async function aqs(){var u=await need();if(!u)return null;var r=await window.s.from('aquariums').select('id,name,aquarium_type,subtype,real_liters,liters,created_at,user_id').eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
function kt(a){var t=String([a&&a.aquarium_type,a&&a.subtype,a&&a.name].join(' ')).toLowerCase();return /fresh|dulce|betta|beta|escala|plant|comunitario/.test(t)?'Dulce / Plantado':'Marino / Reef'}
function lt(a){var l=(a&&a.real_liters!=null&&a.real_liters!=='')?a.real_liters:a&&a.liters;return l?E(l)+' L':'Litros pendientes'}
function cards(x){if(!x||!x.length)return '<article class="dashboard-empty"><h3>🐠 Sin acuarios visibles</h3><p>No hay acuarios visibles para esta sesión.</p><button class="primary" onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Reintentar</button></article>';return x.map(function(a){return '<article class="dashboard-aqua-card" onclick="openA&&openA(\''+E(a.id)+'\')"><div class="dashboard-aqua-cover"><span>🪸</span></div><div class="dashboard-aqua-body"><h3>'+E(a.name||'Acuario')+'</h3><div class="dashboard-aqua-meta"><span>'+E(kt(a))+'</span><span>'+lt(a)+'</span></div><div class="dashboard-aqua-open">Abrir acuario</div></div></article>'}).join('')}
function dashHtml(x,loading){return '<section class="dashboard-hero-main"><div class="dashboard-hero-head"><div><p class="dashboard-hero-kicker">Dashboard premium · AcuarioNexo</p><h2>Mis acuarios</h2><span>'+(loading?'Sincronizando datos desde Supabase...':'Acceso rápido a todos tus acuarios, parámetros, animales y estado general.')+'</span></div><div class="dashboard-hero-actions"><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">🐠 Ver acuarios</button><button onclick="hardRefreshAcuarioNexo&&hardRefreshAcuarioNexo()">↻ Actualizar</button></div></div><div class="dashboard-aquarium-row">'+cards(x||[])+'</div></section><section class="dashboard-ai-card"><h3>🧠 Resumen IA global</h3><p>'+(x&&x.length?'Sistema estable con '+x.length+' acuarios cargados.':'Cargando acuarios guardados.')+'</p></section>'}
function listHtml(x,loading){return '<section class="premium-block aquariums-premium-screen"><div class="block-head"><div><p class="dashboard-hero-kicker">Gestión de acuarios</p><h2>Mis acuarios</h2><p>'+(loading?'Cargando acuarios...':'Abre directamente una ficha o crea un acuario nuevo.')+'</p></div><button class="primary" onclick="formA&&formA()">+ Nuevo</button></div><div class="dashboard-aquarium-row">'+cards(x||[])+'</div></section>'}
async function dashboard(){var u=await need();if(!u)return;render('Dashboard',dashHtml([],true));try{var x=await aqs();render('Dashboard',dashHtml(x,false))}catch(e){render('Dashboard','<section class="card"><h2>Error</h2><div class="error">'+E(e.message)+'</div></section>')}}
async function acs(){var u=await need();if(!u)return;render('Acuarios',listHtml([],true));try{var x=await aqs();render('Acuarios',listHtml(x,false))}catch(e){render('Acuarios','<section class="card"><h2>Error</h2><div class="error">'+E(e.message)+'</div></section>')}}
async function section(n){var u=await need();if(!u)return;if(n==='Parámetros'&&window.q&&window.pars)return window.pars();render(n,'<section class="card"><h2>'+E(n)+'</h2><p>Abre primero un acuario.</p><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Abrir acuarios</button></section>')}
function go(n){set(n);if(n==='Dashboard')return dashboard();if(n==='Acuarios')return acs();return section(n)}
function bind(){window.AcuarioNexoNavigation.safeGo=go;window.goSection=go;window.dashboard=dashboard;window.home=dashboard;window.acs=acs}
async function install(){style();var r=document.getElementById('refreshAppBtn');if(r)r.onclick=function(){location.replace(location.pathname+'?v='+Date.now())};bind();setTimeout(bind,300);setTimeout(bind,900);var u=await user();if(!u)return login();setTimeout(dashboard,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();