window.AcuarioNexoNavigation={version:'core-premium-render-24-05'};
(function(){
function E(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function A(){return document.getElementById('app')}
function active(n){window.acuarionexoActiveNav=n;try{localStorage.setItem('acuarionexo_active_nav',n)}catch(e){}}
function bottom(){return '<nav class="bottom-nav"><button onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="formA&&formA()">＋<small>Añadir</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'Parámetros\')">🧪<small>Parámetros</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'IA\')">🧠<small>IA</small></button></nav>'}
function render(n,h,withNav){var a=A();if(!a)return;active(n);a.innerHTML=h+(withNav===false?'':bottom());scrollTo(0,0)}
function showLogin(msg){var b=document.getElementById('logoutBtn');if(b)b.classList.add('hidden');if(typeof window.login==='function')return window.login();render('Login','<section class="card"><h2>Entrar</h2>'+(msg?'<div class="notice">'+E(msg)+'</div>':'')+'<label>Email</label><input id="em"><label>Contraseña</label><input id="pw" type="password"><button class="primary" onclick="iniciar&&iniciar()">Entrar</button><button onclick="crear&&crear()">Crear cuenta</button><div id="x"></div></section>',false)}
async function hydrate(){if(!window.s)return null;try{var r=await window.s.auth.getSession();window.u=(r.data.session&&r.data.session.user)||null;var b=document.getElementById('logoutBtn');if(b){b.classList.toggle('hidden',!window.u);b.onclick=async function(){try{await window.s.auth.signOut()}catch(e){}try{localStorage.removeItem('acuarionexo_dashboard_aqs');localStorage.removeItem('acuarionexo_active_nav')}catch(e){}location.replace(location.pathname+'?v='+Date.now())}}return window.u}catch(e){window.u=null;return null}}
async function requireUser(){var u=await hydrate();if(!u){showLogin('Sesión no cargada. Entra de nuevo para ver tus acuarios.');return null}return u}
async function getAcuarios(){var u=await requireUser();if(!u)return null;if(!window.s)return [];var cols='id,name,aquarium_type,subtype,real_liters,liters,created_at,user_id';var r=await window.s.from('aquariums').select(cols).eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
function kind(a){var t=String([a&&a.aquarium_type,a&&a.subtype,a&&a.name].join(' ')).toLowerCase();return /fresh|dulce|betta|beta|escala|plant|comunitario/.test(t)?'fresh':'marine'}
function kindText(a){return kind(a)==='fresh'?'Dulce / Plantado':'Marino / Reef'}
function litros(a){var l=(a&&a.real_liters!=null&&a.real_liters!=='')?a.real_liters:a&&a.liters;return l?E(l)+' L':'Litros pendientes'}
function cardList(aqs){if(!aqs||!aqs.length)return '<article class="dashboard-empty"><h3>🐠 Sin acuarios visibles</h3><p>No hay acuarios visibles para esta sesión.</p><button class="primary" onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Reintentar</button></article>';return aqs.map(function(a){var k=kind(a);return '<article class="dashboard-aqua-card" onclick="openA&&openA(\''+E(a.id)+'\')"><div class="dashboard-aqua-cover dashboard-cover-'+k+'"><span>'+(k==='fresh'?'🌿':'🪸')+'</span></div><div class="dashboard-aqua-body"><h3>'+E(a.name||'Acuario')+'</h3><div class="dashboard-aqua-meta"><span>'+E(kindText(a))+'</span><span>'+litros(a)+'</span></div><div class="dashboard-aqua-open">Abrir acuario</div></div></article>'}).join('')}
function dashboardHtml(aqs,loading){return '<section class="dashboard-hero-main"><div class="dashboard-hero-head"><div><p class="dashboard-hero-kicker">Dashboard premium · AcuarioNexo</p><h2>Mis acuarios</h2><span>'+(loading?'Sincronizando datos desde Supabase...':'Acceso rápido a todos tus acuarios, parámetros, animales y estado general.')+'</span></div><div class="dashboard-hero-actions"><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">🐠 Ver acuarios</button><button onclick="hardRefreshAcuarioNexo&&hardRefreshAcuarioNexo()">↻ Actualizar</button></div></div><div class="dashboard-aquarium-row">'+cardList(aqs||[])+'</div></section><section class="dashboard-ai-card"><h3>🧠 Resumen IA global</h3><p>'+(aqs&&aqs.length?'Sistema estable con '+aqs.length+' acuarios cargados. Dashboard preparado para parámetros, avisos, seguimiento visual e historial.':'Pulsa reintentar si no aparecen tus acuarios guardados.')+'</p></section>'}
function acuarioHtml(aqs,loading){return '<section class="premium-block aquariums-premium-screen"><div class="block-head"><div><p class="dashboard-hero-kicker">Gestión de acuarios</p><h2>Mis acuarios</h2><p>'+(loading?'Cargando acuarios...':'Abre directamente una ficha o crea un acuario nuevo.')+'</p></div><button class="primary" onclick="formA&&formA()">+ Nuevo</button></div><div class="dashboard-aquarium-row">'+cardList(aqs||[])+'</div></section>'}
async function acs(){var u=await requireUser();if(!u)return;render('Acuarios',acuarioHtml([],true));try{var aqs=await getAcuarios();if(aqs===null)return;try{localStorage.setItem('acuarionexo_dashboard_aqs',JSON.stringify(aqs))}catch(e){}render('Acuarios',acuarioHtml(aqs,false))}catch(e){render('Acuarios','<section class="card"><h2>Acuarios</h2><div class="error">'+E(e.message||'Error')+'</div><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Reintentar</button></section>')}}
async function dash(){var u=await requireUser();if(!u)return;render('Dashboard',dashboardHtml([],true));try{var aqs=await getAcuarios();if(aqs===null)return;render('Dashboard',dashboardHtml(aqs,false))}catch(e){render('Dashboard','<section class="card"><h2>Inicio</h2><div class="error">'+E(e.message||'Error')+'</div><button onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">Reintentar</button></section>')}}
async function section(n){var u=await requireUser();if(!u)return;if(n==='Parámetros'&&window.q&&window.pars)return window.pars();render(n,'<section class="card"><h2>'+E(n)+'</h2><p>Abre primero un acuario.</p><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Abrir acuarios</button></section>')}
function go(n){if(n==='Dashboard')return dash();if(n==='Acuarios')return acs();return section(n)}
function bind(){window.AcuarioNexoNavigation.active=active;window.AcuarioNexoNavigation.bottom=bottom;window.AcuarioNexoNavigation.render=render;window.AcuarioNexoNavigation.safeGo=go;window.goSection=go;window.acs=acs;window.dashboard=dash;window.home=dash}
async function install(){var r=document.getElementById('refreshAppBtn');if(r)r.onclick=function(){location.replace(location.pathname+'?v='+Date.now())};bind();setTimeout(bind,300);setTimeout(bind,900);var u=await hydrate();if(!u)return showLogin();setTimeout(function(){go('Dashboard')},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();