window.AcuarioNexoNavigation={version:'core-session-safe-24-05'};
(function(){
function E(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function A(){return document.getElementById('app')}
function active(n){window.acuarionexoActiveNav=n;try{localStorage.setItem('acuarionexo_active_nav',n)}catch(e){}}
function top(){return window.menu?window.menu():''}
function bottom(){return '<nav class="bottom-nav"><button onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">🏠<small>Inicio</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">🐠<small>Acuarios</small></button><button onclick="formA&&formA()">＋<small>Añadir</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'Parámetros\')">🧪<small>Parámetros</small></button><button onclick="AcuarioNexoNavigation.safeGo(\'IA\')">🧠<small>IA</small></button></nav>'}
function render(n,h,withNav){var a=A();if(!a)return;active(n);a.innerHTML=(withNav===false?'':top())+h+(withNav===false?'':bottom());scrollTo(0,0)}
function showLogin(msg){var b=document.getElementById('logoutBtn');if(b)b.classList.add('hidden');if(typeof window.login==='function')return window.login();render('Login','<section class="card"><h2>Entrar</h2>'+(msg?'<div class="notice">'+E(msg)+'</div>':'')+'<label>Email</label><input id="em"><label>Contraseña</label><input id="pw" type="password"><button class="primary" onclick="iniciar&&iniciar()">Entrar</button><button onclick="crear&&crear()">Crear cuenta</button><div id="x"></div></section>',false)}
async function hydrate(){if(!window.s)return null;try{var r=await window.s.auth.getSession();window.u=(r.data.session&&r.data.session.user)||null;var b=document.getElementById('logoutBtn');if(b){b.classList.toggle('hidden',!window.u);b.onclick=async function(){try{await window.s.auth.signOut()}catch(e){}try{localStorage.removeItem('acuarionexo_dashboard_aqs');localStorage.removeItem('acuarionexo_active_nav')}catch(e){}location.replace(location.pathname+'?v='+Date.now())}}return window.u}catch(e){window.u=null;return null}}
async function requireUser(){var u=await hydrate();if(!u){showLogin('Sesión no cargada. Entra de nuevo para ver tus acuarios.');return null}return u}
async function getAcuarios(){var u=await requireUser();if(!u)return null;if(!window.s)return [];var cols='id,name,aquarium_type,subtype,real_liters,liters,created_at,user_id';var r=await window.s.from('aquariums').select(cols).eq('user_id',u.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
function cardList(aqs){if(!aqs||!aqs.length)return '<div class="notice">No hay acuarios visibles para esta sesión.</div><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Reintentar</button>';return aqs.map(function(a){var l=(a.real_liters!=null&&a.real_liters!=='')?a.real_liters:a.liters;return '<div class="item"><h3>'+E(a.name||'Acuario')+'</h3><p>'+E(a.aquarium_type||'')+' · '+E(a.subtype||'')+' · '+E(l||'-')+' L</p><button class="primary" onclick="openA&&openA(\''+E(a.id)+'\')">Abrir</button></div>'}).join('')}
async function acs(){var u=await requireUser();if(!u)return;render('Acuarios','<section class="card"><h2>Acuarios</h2><p>Cargando...</p></section>');try{var aqs=await getAcuarios();if(aqs===null)return;try{localStorage.setItem('acuarionexo_dashboard_aqs',JSON.stringify(aqs))}catch(e){}render('Acuarios','<section class="card"><h2>Acuarios</h2><p>'+aqs.length+' acuarios cargados.</p><button class="primary" onclick="formA&&formA()">+ Nuevo</button>'+cardList(aqs)+'</section>')}catch(e){render('Acuarios','<section class="card"><h2>Acuarios</h2><div class="error">'+E(e.message||'Error')+'</div><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Reintentar</button></section>')}}
async function dash(){var u=await requireUser();if(!u)return;render('Dashboard','<section class="card"><h2>Inicio</h2><p>Cargando acuarios...</p></section>');try{var aqs=await getAcuarios();if(aqs===null)return;render('Dashboard','<section class="card"><h2>Mis acuarios</h2><p>'+aqs.length+' acuarios disponibles.</p>'+cardList(aqs)+'</section>')}catch(e){render('Dashboard','<section class="card"><h2>Inicio</h2><div class="error">'+E(e.message||'Error')+'</div><button onclick="AcuarioNexoNavigation.safeGo(\'Dashboard\')">Reintentar</button></section>')}}
async function section(n){var u=await requireUser();if(!u)return;if(n==='Parámetros'&&window.q&&window.pars)return window.pars();render(n,'<section class="card"><h2>'+E(n)+'</h2><p>Abre primero un acuario.</p><button onclick="AcuarioNexoNavigation.safeGo(\'Acuarios\')">Abrir acuarios</button></section>')}
function go(n){if(n==='Dashboard')return dash();if(n==='Acuarios')return acs();return section(n)}
function bind(){window.AcuarioNexoNavigation.active=active;window.AcuarioNexoNavigation.bottom=bottom;window.AcuarioNexoNavigation.render=render;window.AcuarioNexoNavigation.safeGo=go;window.goSection=go;window.acs=acs;window.dashboard=dash;window.home=dash}
async function install(){var r=document.getElementById('refreshAppBtn');if(r)r.onclick=function(){location.replace(location.pathname+'?v='+Date.now())};bind();setTimeout(bind,300);setTimeout(bind,900);var u=await hydrate();if(!u)return showLogin();setTimeout(function(){go('Dashboard')},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();