/* AcuarioNexo · Parámetros por acuario y fechas · lógica limpia */
(function(){
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
function schema(k){return (window.MEASUREMENT_SCHEMA&&window.MEASUREMENT_SCHEMA.parameters&&window.MEASUREMENT_SCHEMA.parameters[k])||(window.MeasurementSchema&&window.MeasurementSchema.parameters&&window.MeasurementSchema.parameters[k])||{}}
function mode(){try{return window.AcuarioNexoMeasurementAI&&window.AcuarioNexoMeasurementAI.detectAquariumMode&&window.AcuarioNexoMeasurementAI.detectAquariumMode(window.q)==='freshwater'?'freshwater':'marine'}catch(e){return'marine'}}
function keys(){return (window.MEASUREMENT_SCHEMA&&window.MEASUREMENT_SCHEMA.mainByMode&&window.MEASUREMENT_SCHEMA.mainByMode[mode()])||(window.MeasurementSchema&&window.MeasurementSchema.mainByMode&&window.MeasurementSchema.mainByMode[mode()])||[]}
function rows(){return window.__aq_rows||[]}
function label(k){return (schema(k).label||k).replace('Salinidad / Densidad','Salinidad').replace('Fosfato PO4','PO4').replace('Nitrato NO3','NO3').replace('Nitrito NO2','NO2').replace('KH / Alcalinidad','KH').replace('Calcio Ca','Calcio').replace('Magnesio Mg','Magnesio')}
async function load(){var r=await window.s.from('aquarium_measurements').select('*').eq('aquarium_id',window.q.id).order('measured_at',{ascending:false});if(r.error)throw r.error;window.__aq_rows=r.data||[]}
function parseRaw(x){var n=Number(String(x||'').replace(',','.').replace(/[<>= ]/g,''));return Number.isFinite(n)?n:null}
function latest(k){for(var i=0;i<rows().length;i++){if(rows()[i].parameter_key===k)return rows()[i]}return null}
function fmt(k,r){if(!r)return{main:'—',unit:''};var txt=String(r.display_value||r.normalized_value||r.raw_text||'—').trim().replace(/^=\s*/,'');var m=txt.match(/^([^a-zA-Z°µ]+)\s*(.*)$/);return{main:(m?m[1]:txt).trim(),unit:(m?m[2]:'').trim()}}
function st(r){if(!r)return{label:'Sin datos',cls:'p-empty'};if(['red','purple'].indexOf(r.color)>=0||r.risk_level==='high'||r.risk_level==='critical')return{label:'Crítico',cls:'p-bad'};if(['yellow','orange'].indexOf(r.color)>=0||r.risk_level==='medium')return{label:'Cuidado',cls:'p-warn'};return{label:'Bien',cls:'p-ok'}}
function dateKey(r){var d=r&&r.measured_at?new Date(r.measured_at):new Date();return d.toISOString().slice(0,10)}
function dateLabel(k){var p=k.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:k}
function grouped(){var g={};for(var i=0;i<rows().length;i++){var r=rows()[i],k=dateKey(r);if(!g[k])g[k]=[];g[k].push(r)}return Object.keys(g).sort().reverse().map(function(k){return{date:k,items:g[k]}})}
function resultBox(r){var si=st(r),fv=fmt(r.parameter_key,r);return'<div class="date-param '+si.cls+'"><b>'+esc(label(r.parameter_key))+'</b><strong>'+esc(fv.main)+(fv.unit?' '+esc(fv.unit):'')+'</strong><span class="status-pill">'+esc(si.label)+'</span><small>'+esc(r.test_method_label||'')+'</small></div>'}
function aquariumSummary(){var kh=latest('alkalinity_dkh')||latest('kh'),po4=latest('phosphate_po4')||latest('po4'),no3=latest('nitrate_no3')||latest('no3');return'<div class="param-aq-card"><h3>'+esc(window.q.name)+'</h3><div class="param-aq-meta"><span>'+esc(mode()==='freshwater'?'Dulce':'Marino/Reef')+'</span><span>'+esc(window.q.real_liters||window.q.liters||'-')+' L</span><span>'+rows().length+' mediciones</span></div><div class="param-kpis"><div class="param-kpi"><small>KH</small><b>'+esc(fmt('alkalinity_dkh',kh).main)+'</b></div><div class="param-kpi"><small>NO3</small><b>'+esc(fmt('nitrate_no3',no3).main)+'</b></div><div class="param-kpi"><small>PO4</small><b>'+esc(fmt('phosphate_po4',po4).main)+'</b></div></div><div class="param-actions"><button onclick="startGuidedMeasurements()" class="primary">Nueva medición</button><button onclick="showLatestParams()">Últimos valores</button></div></div>'}
function dateAccordion(){var gs=grouped();if(!gs.length)return'<div class="date-card"><summary>Sin mediciones todavía</summary></div>';return'<div class="date-list">'+gs.map(function(g,i){return'<details class="date-card" '+(i===0?'open':'')+'><summary>'+dateLabel(g.date)+' <span>'+g.items.length+' resultados</span></summary><div class="date-body">'+g.items.map(resultBox).join('')+'</div></details>'}).join('')+'</div>'}
function latestGrid(){return'<div class="date-body">'+keys().map(function(k){var r=latest(k);return r?resultBox(r):''}).join('')+'</div>'}
function render(){window.S(window.am()+'<section class="card param-screen"><h2>Parámetros</h2>'+aquariumSummary()+'<h3>Historial por fechas</h3>'+dateAccordion()+'</section>')}
window.showLatestParams=function(){window.S(window.am()+'<section class="card param-screen"><button onclick="pars()">← Historial</button><h2>Últimos valores</h2>'+aquariumSummary()+latestGrid()+'</section>')}
window.pars=async function(){try{await load();render()}catch(e){window.S(window.am()+'<section class="card error">'+esc(e.message)+'</section>')}};
function baseMeasurement(k){var raw=String(document.getElementById('gm_val').value||'').trim(),cmp=document.getElementById('gm_cmp').value||'=',method=document.getElementById('gm_met').value||'Manual/Otro',notes=document.getElementById('gm_no').value||'',measured=new Date(document.getElementById('gm_date').value).toISOString(),sc=schema(k),n=parseRaw(raw),unit=sc.unit||'';return{user_id:window.u.id,aquarium_id:window.q.id,measured_at:measured,parameter_key:k,parameter_label:sc.label||k,category:sc.category||'general',test_method_key:String(method).toLowerCase().replace(/[^a-z0-9]+/g,'_'),test_method_label:method,comparator:cmp,raw_value:n,raw_text:raw,raw_unit:unit,normalized_value:n,normalized_unit:unit,display_value:(cmp+' '+raw+(unit?' '+unit:'')).trim(),display_original:(cmp+' '+raw+(unit?' '+unit:'')).trim(),status:'unknown',color:'gray',risk_level:'low',notes:notes,source:'acuarionexo-guided',payload:{aquarium_name:window.q.name||'',fallback:true}}}
function build(k){var input={user_id:window.u.id,aquarium_id:window.q.id,parameter_key:k,raw_text:document.getElementById('gm_val').value,comparator:document.getElementById('gm_cmp').value,test_method_label:document.getElementById('gm_met').value,notes:document.getElementById('gm_no').value,measured_at:new Date(document.getElementById('gm_date').value).toISOString()};try{if(window.AcuarioNexoMeasurementEngine&&window.AcuarioNexoMeasurementEngine.buildMeasurement)return window.AcuarioNexoMeasurementEngine.buildMeasurement(input,window.q)}catch(e){}return baseMeasurement(k)}
window.startGuidedMeasurements=function(){window.__guided={keys:keys(),i:0,items:[],date:new Date().toISOString().slice(0,16)};showGuided()};
function showGuided(){var g=window.__guided,k=g.keys[g.i],p=schema(k),dots=g.keys.map(function(_,i){return'<i class="'+(i<g.i?'done':(i===g.i?'on':''))+'"></i>'}).join('');window.S(window.am()+'<section class="card guided-box"><button onclick="pars()">← Salir</button><h2>Medición guiada</h2><div class="guided-progress">'+dots+'</div><h3>'+esc(label(k))+'</h3><p>'+(g.i+1)+' de '+g.keys.length+'</p><label>Fecha/hora</label><input id="gm_date" type="datetime-local" value="'+esc(g.date)+'" onchange="window.__guided.date=this.value"><label>Método / test</label><select id="gm_met" onchange="previewGuided(\''+k+'\')">'+((p.methods||['Manual/Otro']).map(function(m){return'<option>'+esc(m)+'</option>'}).join(''))+'</select><label>Comparador</label><select id="gm_cmp" onchange="previewGuided(\''+k+'\')"><option>=</option><option>&lt;</option><option>&gt;</option><option>&lt;=</option><option>&gt;=</option></select><label>Lectura del test</label><input id="gm_val" inputmode="decimal" oninput="previewGuided(\''+k+'\')" placeholder="Valor leído"><div id="gm_prev" class="convert">Introduce lectura para ver conversión.</div><label>Notas</label><textarea id="gm_no"></textarea><div class="grid"><button onclick="skipGuided()">Saltar</button><button class="primary" onclick="addGuided(\''+k+'\')">Guardar y siguiente</button></div></section>')}
window.previewGuided=function(k){try{var b=build(k),el=document.getElementById('gm_prev');if(el)el.innerHTML='<b>Se guardará:</b> '+esc(b.display_value)+'<br><small>Original: '+esc(b.display_original)+'</small>'}catch(e){var er=document.getElementById('gm_prev');if(er)er.textContent='Introduce lectura para ver conversión.'}};
window.addGuided=function(k){var raw=String(document.getElementById('gm_val').value||'').trim();if(raw)window.__guided.items.push(build(k));window.__guided.i++;if(window.__guided.i>=window.__guided.keys.length)finishGuided();else showGuided()};
window.skipGuided=function(){window.__guided.i++;if(window.__guided.i>=window.__guided.keys.length)finishGuided();else showGuided()};
function finishGuided(){var g=window.__guided;window.S(window.am()+'<section class="card"><h2>Confirmar mediciones</h2><p>'+g.items.length+' mediciones preparadas.</p>'+g.items.map(function(x){return'<div class="item"><b>'+esc(x.parameter_label)+'</b><p>'+esc(x.display_value)+' · '+esc(x.test_method_label)+'</p></div>'}).join('')+'<button class="primary" onclick="saveGuidedBatch()">Guardar todo</button><button onclick="pars()">Cancelar</button><div id="x"></div></section>')}
window.saveGuidedBatch=async function(){try{var g=window.__guided;if(!g.items.length)return pars();var r=await window.s.from('aquarium_measurements').insert(g.items);if(r.error)throw r.error;window.__guided=null;await pars()}catch(e){document.getElementById('x').innerHTML='<div class="error">'+esc(e.message)+'</div>'}};
window.openParam=function(k){window.showLatestParams()};
})();