/* AcuarioNexo · Parámetros · flujo limpio + estado API */
(function(){
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]})}
function schema(k){return (window.MEASUREMENT_SCHEMA&&window.MEASUREMENT_SCHEMA.parameters&&window.MEASUREMENT_SCHEMA.parameters[k])||(window.MeasurementSchema&&window.MeasurementSchema.parameters&&window.MeasurementSchema.parameters[k])||{}}
function mode(){try{return window.AcuarioNexoAPI?window.AcuarioNexoAPI.aquariumMode(window.q):(window.AcuarioNexoMeasurementAI&&window.AcuarioNexoMeasurementAI.detectAquariumMode(window.q)==='freshwater'?'freshwater':'marine')}catch(e){return'marine'}}
function mainKeys(){return window.AcuarioNexoAPI?window.AcuarioNexoAPI.mainKeys(window.q):((window.MEASUREMENT_SCHEMA&&window.MEASUREMENT_SCHEMA.mainByMode&&window.MEASUREMENT_SCHEMA.mainByMode[mode()])||(window.MeasurementSchema&&window.MeasurementSchema.mainByMode&&window.MeasurementSchema.mainByMode[mode()])||[])}
function allKeys(){var p=(window.MEASUREMENT_SCHEMA&&window.MEASUREMENT_SCHEMA.parameters)||(window.MeasurementSchema&&window.MeasurementSchema.parameters)||{},a=mainKeys().slice(),seen={};a.forEach(function(k){seen[k]=1});Object.keys(p).forEach(function(k){if(!seen[k])a.push(k)});return a}
function rows(){return window.__aq_rows||[]}
function label(k){return (schema(k).label||k).replace('Salinidad / Densidad','Salinidad').replace('Fosfato PO4','PO4').replace('Nitrato NO3','NO3').replace('Nitrito NO2','NO2').replace('KH / Alcalinidad','KH').replace('Calcio Ca','Calcio').replace('Magnesio Mg','Magnesio')}
async function load(){var r=await window.s.from('aquarium_measurements').select('*').eq('aquarium_id',window.q.id).order('measured_at',{ascending:false});if(r.error)throw r.error;window.__aq_rows=r.data||[]}
function parseRaw(x){var n=Number(String(x||'').replace(',','.').replace(/[<>= ]/g,''));return Number.isFinite(n)?n:null}
function latest(k){for(var i=0;i<rows().length;i++){if(rows()[i].parameter_key===k)return rows()[i]}return null}
function fmt(r){if(!r)return{main:'-',unit:''};var t=String(r.display_value||r.normalized_value||r.raw_text||'-').replace(/^=\s*/,'').trim(),m=t.match(/^([^a-zA-Z°µ]+)\s*(.*)$/);return{main:(m?m[1]:t).trim(),unit:(m?m[2]:'').trim()}}
function st(r){if(!r)return{label:'Sin datos',cls:'p-empty'};if(['red','purple'].indexOf(r.color)>=0||r.risk_level==='high'||r.risk_level==='critical')return{label:'Crítico',cls:'p-bad'};if(['yellow','orange'].indexOf(r.color)>=0||r.risk_level==='medium')return{label:'Cuidado',cls:'p-warn'};return{label:'Bien',cls:'p-ok'}}
function dateKey(r){var d=r&&r.measured_at?new Date(r.measured_at):new Date();return d.toISOString().slice(0,10)}
function dateLabel(k){var p=k.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:k}
function resultBox(r){var s=st(r),f=fmt(r);return '<div class="date-param '+s.cls+'"><b>'+esc(label(r.parameter_key))+'</b><strong>'+esc(f.main)+(f.unit?' '+esc(f.unit):'')+'</strong><span class="status-pill">'+esc(s.label)+'</span><small>'+esc(r.test_method_label||'')+'</small></div>'}
function aiRow(r){var s=st(r);return '<div class="item '+(s.cls==='p-bad'?'error':s.cls==='p-warn'?'notice':'')+'"><b>'+esc(label(r.parameter_key))+' · '+esc(r.ai_title||s.label)+'</b><p>'+esc(r.ai_summary||r.display_value||'')+'</p><p class="small">'+esc(r.ai_recommendation||'')+'</p><p class="small"><b>Siguiente:</b> '+esc(r.ai_next_action||'Registrar evolución.')+'</p></div>'}
function latestMainRows(){return mainKeys().map(function(k){return latest(k)}).filter(Boolean)}
function waterChangePanel(){var plan=null;try{plan=window.AcuarioNexoMeasurementAI&&window.AcuarioNexoMeasurementAI.waterChangePlan(window.q,rows())}catch(e){}if(!plan)return '';var cls=plan.level==='urgent'||plan.level==='high'?'error':plan.level==='watch'?'notice':'success';return '<section class="panel"><h3>IA cambios de agua</h3><div class="'+cls+'"><b>'+esc(plan.title)+'</b><p>'+esc(plan.percent)+' · '+esc(plan.when)+'</p><p>'+esc(plan.reason)+'</p><p class="small"><b>Acción:</b> '+esc(plan.action)+'</p></div></section>'}
function aiPanel(){var rs=latestMainRows();if(!rs.length)return '<section class="panel"><h3>IA parámetros</h3><div class="notice">Aún no hay mediciones suficientes para evaluar este acuario.</div></section>'+waterChangePanel();var issues=rs.filter(function(r){var x=st(r);return x.cls==='p-bad'||x.cls==='p-warn'});if(!issues.length)return '<section class="panel"><h3>IA parámetros</h3><div class="success">Los últimos parámetros principales están dentro de rango. Mantén rutina y registra evolución.</div></section>'+waterChangePanel();return '<section class="panel"><h3>IA parámetros</h3>'+issues.map(aiRow).join('')+'</section>'+waterChangePanel()}
function grouped(){var g={};rows().forEach(function(r){var k=dateKey(r);(g[k]=g[k]||[]).push(r)});return Object.keys(g).sort().reverse().map(function(k){return{date:k,items:g[k]}})}
function dateAccordion(){var gs=grouped();if(!gs.length)return '<div class="date-card"><summary>Sin mediciones todavía</summary></div>';return '<div class="date-list">'+gs.map(function(g,i){return '<details class="date-card" '+(i===0?'open':'')+'><summary>'+dateLabel(g.date)+' <span>'+g.items.length+' resultados</span></summary><div class="date-body">'+g.items.map(resultBox).join('')+'</div></details>'}).join('')+'</div>'}
function aquariumSummary(){var kh=latest('kh_dkh')||latest('alkalinity_dkh')||latest('kh'),no3=latest('nitrate_no3')||latest('no3'),po4=latest('phosphate_po4')||latest('po4');return '<div class="param-aq-card"><h3>'+esc(window.q.name)+'</h3><div class="param-aq-meta"><span>'+esc(mode()==='freshwater'?'Dulce':'Marino/Reef')+'</span><span>'+esc(window.q.real_liters||window.q.liters||'-')+' L</span><span>'+rows().length+' mediciones</span></div><div class="param-kpis"><div class="param-kpi"><small>KH</small><b>'+esc(fmt(kh).main)+'</b></div><div class="param-kpi"><small>NO3</small><b>'+esc(fmt(no3).main)+'</b></div><div class="param-kpi"><small>PO4</small><b>'+esc(fmt(po4).main)+'</b></div></div><div class="param-actions"><button class="primary" onclick="startSingleMeasurement()">Medición individual</button><button onclick="startRoutineMeasurements()">Rutina completa</button></div><div class="param-actions"><button onclick="showLatestParams()">Últimos valores</button><button onclick="pars()">Historial</button></div></div>'}
function localState(){var now=new Date(),freq={temperature_c:1,salinity_ppt:2,specific_gravity:2,ph:2,kh_dkh:3,nitrite_no2:7,nitrate_no3:7,phosphate_po4:7,calcium_ca:14,magnesium_mg:14,potassium_k:30,gh:14,ammonia_nh3:7,tds:14,conductivity:14,co2:7,iron_fe:14};var items=mainKeys().map(function(k){var r=latest(k),f=freq[k]||14,next=null,late=0;if(r){var d=new Date(r.measured_at||r.created_at);next=new Date(d.getTime()+f*86400000);late=Math.max(0,Math.floor((now-next)/86400000))}var ss=st(r);return{key:k,label:label(k),latest:r,status:r?(late>0?'retrasado':ss.label.toLowerCase()):'pendiente',delayed:late>0,next:next?next.toISOString():null,daysLate:late}});return{items:items,pending:items.filter(function(x){return !x.latest}),delayed:items.filter(function(x){return x.delayed}),next:items.filter(function(x){return x.next}).sort(function(a,b){return new Date(a.next)-new Date(b.next)})[0]||null,overall:items.some(function(x){return !x.latest})?'incompleto':items.some(function(x){return x.delayed})?'retrasado':'correcto'}}
async function roadmapSummary(){var stt;try{stt=window.AcuarioNexoAPI?await window.AcuarioNexoAPI.parameterState(window.q):localState()}catch(e){stt=localState()}var cls={pendiente:'p-empty',correcto:'p-ok',bien:'p-ok',retrasado:'p-warn',revisar:'p-warn','crítico':'p-bad'};return '<div class="param-aq-card"><h3>Estado del acuario</h3><div class="date-body">'+stt.items.map(function(i){var c=cls[i.status]||'p-empty',extra=i.delayed&&i.daysLate?' · '+i.daysLate+' días tarde':'';return '<div class="date-param '+c+'"><b>'+esc(i.label)+'</b><strong>'+esc(i.status)+extra+'</strong><span class="status-pill">'+esc(i.latest?'medido':'pendiente')+'</span></div>'}).join('')+'</div><div class="param-aq-meta"><span>Próxima medición: '+esc(stt.next?stt.next.label:'Sin datos')+'</span><span>Estado general: '+esc(stt.overall)+'</span></div></div>'}
async function render(){var summary=await roadmapSummary();window.S(window.am()+'<section class="card param-screen"><h2>Parámetros</h2>'+aquariumSummary()+summary+'<h3>Historial por fechas</h3>'+dateAccordion()+'</section>'+aiPanel())}
window.pars=async function(){try{await load();await render()}catch(e){window.S(window.am()+'<section class="card error">'+esc(e.message)+'</section>')}};
window.showLatestParams=function(){var html=mainKeys().map(function(k){var r=latest(k);return r?resultBox(r):'<div class="date-param p-empty"><b>'+esc(label(k))+'</b><strong>Pendiente</strong><span class="status-pill">Sin datos</span></div>'}).join('');window.S(window.am()+'<section class="card param-screen"><button onclick="pars()">← Historial</button><h2>Últimos valores</h2>'+aquariumSummary()+'<div class="date-body">'+html+'</div></section>'+aiPanel())};
function baseMeasurement(k){var raw=String(document.getElementById('gm_val').value||'').trim(),cmp=document.getElementById('gm_cmp').value||'=',method=document.getElementById('gm_met').value||'Manual/Otro',notes=document.getElementById('gm_no').value||'',date=new Date(document.getElementById('gm_date').value).toISOString(),sc=schema(k),n=parseRaw(raw),unit=sc.unit||'';return{user_id:window.u.id,aquarium_id:window.q.id,measured_at:date,parameter_key:k,parameter_label:sc.label||k,category:sc.category||'general',test_method_key:String(method).toLowerCase().replace(/[^a-z0-9]+/g,'_'),test_method_label:method,comparator:cmp,raw_value:n,raw_text:raw,raw_unit:unit,normalized_value:n,normalized_unit:unit,display_value:(cmp+' '+raw+(unit?' '+unit:'')).trim(),display_original:(cmp+' '+raw+(unit?' '+unit:'')).trim(),status:'unknown',color:'gray',risk_level:'low',notes:notes,source:'acuarionexo-parameters',payload:{aquarium_name:window.q.name||'',fallback:true}}}
function build(k){var input={user_id:window.u.id,aquarium_id:window.q.id,parameter_key:k,raw_text:document.getElementById('gm_val').value,comparator:document.getElementById('gm_cmp').value,test_method_label:document.getElementById('gm_met').value,notes:document.getElementById('gm_no').value,measured_at:new Date(document.getElementById('gm_date').value).toISOString()};try{if(window.AcuarioNexoMeasurementEngine&&window.AcuarioNexoMeasurementEngine.buildMeasurement)return window.AcuarioNexoMeasurementEngine.buildMeasurement(input,window.q)}catch(e){}return baseMeasurement(k)}
function paramSelect(k){return '<label>Parámetro</label><select id="gm_param" onchange="changeGuidedParam(this.value)">'+allKeys().map(function(x){return '<option value="'+esc(x)+'" '+(x===k?'selected':'')+'>'+esc(label(x))+'</option>'}).join('')+'</select>'}
window.startSingleMeasurement=function(k){window.__guided={mode:'single',keys:[k||mainKeys()[0]||allKeys()[0]],i:0,items:[],date:new Date().toISOString().slice(0,16)};showForm()};
window.startRoutineMeasurements=function(){window.__guided={mode:'routine',keys:mainKeys(),i:0,items:[],date:new Date().toISOString().slice(0,16)};showForm()};
window.startGuidedMeasurements=window.startSingleMeasurement;
window.changeGuidedParam=function(k){window.__guided.keys=[k];window.__guided.i=0;showForm()};
function showForm(){var g=window.__guided,k=g.keys[g.i],p=schema(k),routine=g.mode==='routine',dots=routine?'<div class="guided-progress">'+g.keys.map(function(_,i){return '<i class="'+(i<g.i?'done':(i===g.i?'on':''))+'"></i>'}).join('')+'</div>':'',methods=(p.methods||['Manual/Otro']).map(function(m){return '<option>'+esc(m)+'</option>'}).join(''),sub=routine?'Rutina completa · '+(g.i+1)+' de '+g.keys.length:'Medición individual';window.S(window.am()+'<section class="card guided-box"><button onclick="pars()">← Salir</button><p class="small">'+sub+'</p><h2>'+esc(label(k))+'</h2><p class="small">'+esc(k)+'</p>'+dots+(routine?'':paramSelect(k))+'<label>Fecha/hora</label><input id="gm_date" type="datetime-local" value="'+esc(g.date)+'" onchange="window.__guided.date=this.value"><label>Método / test</label><select id="gm_met" onchange="previewGuided(\''+k+'\')">'+methods+'</select><label>Comparador</label><select id="gm_cmp" onchange="previewGuided(\''+k+'\')"><option>=</option><option>&lt;</option><option>&gt;</option><option>&lt;=</option><option>&gt;=</option></select><label>Lectura del test</label><input id="gm_val" inputmode="decimal" oninput="previewGuided(\''+k+'\')" placeholder="Valor leído"><div id="gm_prev" class="convert">Introduce lectura para ver conversión.</div><label>Notas</label><textarea id="gm_no"></textarea><div class="grid"><button onclick="skipGuided()">Saltar</button><button class="primary" onclick="addGuided(\''+k+'\')">'+(routine?'Guardar y siguiente':'Guardar medición')+'</button></div></section>')}
window.previewGuided=function(k){var el=document.getElementById('gm_prev');try{var b=build(k);if(el)el.innerHTML='<b>Se guardará:</b> '+esc(b.display_value)+'<br><small>Original: '+esc(b.display_original)+'</small><br><small><b>IA:</b> '+esc(b.ai_title||'Lectura preparada')+' · '+esc(b.ai_next_action||'Registrar evolución.')+'</small>'}catch(e){if(el)el.textContent='Introduce lectura para ver conversión.'}};
window.addGuided=function(k){var raw=String(document.getElementById('gm_val').value||'').trim();if(raw)window.__guided.items.push(build(k));if(window.__guided.mode==='single')return finishGuided();window.__guided.i++;window.__guided.i>=window.__guided.keys.length?finishGuided():showForm()};
window.skipGuided=function(){if(window.__guided.mode==='single')return pars();window.__guided.i++;window.__guided.i>=window.__guided.keys.length?finishGuided():showForm()};
function finishGuided(){var g=window.__guided;window.S(window.am()+'<section class="card"><h2>Confirmar mediciones</h2><p>'+g.items.length+' mediciones preparadas.</p>'+g.items.map(function(x){return '<div class="item"><b>'+esc(x.parameter_label)+'</b><p>'+esc(x.display_value)+' · '+esc(x.test_method_label)+'</p><p class="small"><b>IA:</b> '+esc(x.ai_title||'Lectura preparada')+' · '+esc(x.ai_recommendation||'')+'</p></div>'}).join('')+'<button class="primary" onclick="saveGuidedBatch()">Guardar todo</button><button onclick="pars()">Cancelar</button><div id="x"></div></section>')}
window.saveGuidedBatch=async function(){try{var g=window.__guided;if(!g.items.length)return pars();var r=await window.s.from('aquarium_measurements').insert(g.items);if(r.error)throw r.error;window.__guided=null;await pars()}catch(e){document.getElementById('x').innerHTML='<div class="error">'+esc(e.message)+'</div>'}};
window.openParam=function(k){window.startSingleMeasurement(k)};
})();