const c=window.ACUARIONEXO_CONFIG;
const s=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_KEY);
const A=document.getElementById('app');
let U=null;
const cats={sal:'Sal',medicamento:'Medicamento',bacteria:'Bacteria',comida:'Comida',test:'Test',aditivo:'Aditivo',consumible:'Consumible'};
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function v(id){return document.getElementById(id)?.value?.trim()||''}
function screen(html){A.innerHTML=html;scrollTo(0,0)}
function notice(t){return `<div class='card'>${esc(t)}</div>`}
async function boot(){const r=await s.auth.getSession();U=r.data.session?.user||null;document.getElementById('loginBtn').onclick=()=>location.href='../index.html';screenHome()}
window.screenHome=function(){screen(`<section class='card'><h2>Studio Fichas IA gratis</h2><p>Crea fichas técnicas reutilizables para el inventario inteligente de AcuarioNexo.</p><span class='tag'>Sin API de pago</span><span class='tag'>Revisión manual</span><span class='tag'>Supabase</span></section><section class='card'><h3>Flujo correcto</h3><ol><li>Pegas texto del fabricante o datos de la etiqueta.</li><li>El asistente estructura la ficha.</li><li>Tú revisas antes de guardar.</li><li>AcuarioNexo podrá usar la ficha para cálculos de stock, dosis, cambios de agua y tratamientos.</li></ol></section><section class='card'><button onclick='screenNewFicha()'>Crear ficha técnica</button><button onclick='screenList()'>Ver fichas guardadas</button></section>`)};
window.screenNewFicha=function(){screen(`<section class='card'><h2>Nueva ficha técnica</h2><label>Foto o etiqueta del producto</label><input id='foto' type='file' accept='image/*'><label>Texto del fabricante / etiqueta / web</label><textarea id='textoFuente' placeholder='Pega aquí dosis, composición, instrucciones, advertencias...'></textarea><button onclick='buildFichaFromText()'>Asistente gratuito: estructurar ficha</button></section><section class='card'><label>Tipo</label><select id='tipo'>${Object.entries(cats).map(([k,n])=>`<option value='${k}'>${n}</option>`).join('')}</select><label>Marca</label><input id='marca'><label>Nombre comercial</label><input id='nombre'><label>Resumen corto</label><textarea id='resumen'></textarea><label>Dosis fabricante</label><textarea id='dosis'></textarea><label>Litros tratados / cálculo</label><textarea id='modo'></textarea><label>Composición / ingredientes</label><textarea id='tecnica'></textarea><label>Compatibilidad</label><textarea id='compatibilidad'></textarea><label>Advertencias / cuándo no usar</label><textarea id='advertencias'></textarea><label>Parámetros relacionados</label><input id='params' placeholder='KH, Ca, Mg, NO3, PO4...'><label>Notas de revisión</label><textarea id='notas'></textarea><button onclick='saveFicha()'>Guardar ficha revisada</button><div id='x'></div></section>`)};
window.buildFichaFromText=function(){const t=v('textoFuente');if(!t){document.getElementById('x')&&(document.getElementById('x').innerHTML=notice('Pega primero texto del fabricante.'));return}const low=t.toLowerCase();if(low.includes('salt')||low.includes('sal ')||low.includes('35 g'))document.getElementById('tipo').value='sal';if(low.includes('medic')||low.includes('treat')||low.includes('tratamiento'))document.getElementById('tipo').value='medicamento';if(low.includes('bacteria'))document.getElementById('tipo').value='bacteria';if(low.includes('food')||low.includes('alimento')||low.includes('comida'))document.getElementById('tipo').value='comida';if(low.includes('test')||low.includes('reactivo'))document.getElementById('tipo').value='test';const lines=t.split(/\n|\.|;/).map(x=>x.trim()).filter(Boolean);const dose=lines.filter(x=>/ml|g|gram|gota|litro|l\b|ppm|dosis|dose|cada|por/i.test(x)).slice(0,8).join('\n');const warn=lines.filter(x=>/no usar|warning|advert|precau|peligro|mantener|niños|reef|invertebr|coral/i.test(x)).slice(0,8).join('\n');document.getElementById('dosis').value=dose||document.getElementById('dosis').value;document.getElementById('advertencias').value=warn||document.getElementById('advertencias').value;document.getElementById('tecnica').value=t.slice(0,2500);document.getElementById('resumen').value='Ficha generada desde texto del fabricante. Revisar antes de aprobar.';document.getElementById('notas').value='Pendiente revisión manual. IA gratuita local/reglas, sin API de pago.'};
window.saveFicha=async function(){try{if(!U)throw new Error('Debes iniciar sesión desde AcuarioNexo.');const row={user_id:U.id,modulo:'inventario',tipo_ficha:v('tipo'),subtipo:v('tipo'),categoria:v('tipo'),marca:v('marca'),nombre:v('nombre')||'Sin nombre',nombre_comercial:v('nombre'),resumen_corto:v('resumen'),dosis:v('dosis'),modo_de_uso:v('modo'),ficha_tecnica:v('tecnica'),compatibilidad:v('compatibilidad'),advertencias:v('advertencias'),parametros_relacionados:v('params')?v('params').split(',').map(x=>x.trim()).filter(Boolean):[],notas_admin:v('notas'),estado:'borrador',nivel_confianza:0.4,ficha_normalizada:{origen:'studio-fichas-gratis',revision:'manual_pendiente',campos:['dosis','compatibilidad','advertencias','modo_de_uso']}};const r=await s.from('nexoadmin_fichas').insert(row);if(r.error)throw r.error;document.getElementById('x').innerHTML='<div class="card">Ficha guardada como borrador.</div>'}catch(e){document.getElementById('x').innerHTML='<div class="card">'+esc(e.message)+'</div>'}};
function fichaHtml(f){return `<div class='ficha'><span class='tag'>${esc(cats[f.tipo_ficha]||f.tipo_ficha||f.categoria||'Ficha')}</span><h3>${esc(f.nombre||f.nombre_comercial||'Sin nombre')}</h3><p>${esc(f.marca||'')}</p><p>${esc(f.resumen_corto||'')}</p><details><summary>Ver técnica</summary><p>${esc(f.dosis||'Sin dosis')}</p><p>${esc(f.advertencias||'Sin advertencias')}</p></details></div>`}
window.screenList=async function(){if(!U)return screen(`<section class='card'><p>Inicia sesión desde AcuarioNexo primero.</p></section>`);screen(`<section class='card'><h2>Fichas</h2><p>Cargando...</p></section>`);const r=await s.from('nexoadmin_fichas').select('*').eq('modulo','inventario').order('created_at',{ascending:false}).limit(100);if(r.error)return screen(`<section class='card'>${esc(r.error.message)}</section>`);screen(`<section class='card'><h2>Fichas creadas</h2>${(r.data||[]).map(fichaHtml).join('')||'<p>No hay fichas todavía.</p>'}</section>`)};
boot();
